### ISSUE TITLE
TCP established metrics for ECS containers

### ISSUE THREAD

**Issue by kollektiv** [aws/amazon-cloudwatch-agent#100]
We are running containers using the ECS optimized AMI and have installed the cloudwatch agent. The cloudwatch agent is configured to emit the TCP established metric `netstat_tcp_established`, however the metric does not account for TCP connections made by containers. Can the cloudwatch agent support accounting for containers for netstat metrics?

**Comment by haojhcwa** [comment]
Hi Thank you for your feedback,
I'd like to clarify that do you mean currently you are running a cloudwatch agent on a EC2 instance running a ECS optimized AMI, and the agent is only reporting the TCP connections of the instance, but does not contain the TCP connections created by the containers running on the instance?

We will have to do some research to see the viability of this feature request.

**Comment by kollektiv** [comment]
Hello

> I'd like to clarify that do you mean currently you are running a cloudwatch agent on a EC2 instance running a ECS optimized AMI, and the agent is only reporting the TCP connections of the instance, but does not contain the TCP connections created by the containers running on the instance?

Yes, and digging deeper into this, the TCP connections created by containers when running in host networking mode are reported. When containers are running in awsvpc networking mode the TCP connections are not reported
