### ISSUE TITLE
Failed to start CloudWatch agent on ubuntu22.04

### ISSUE THREAD

**Issue by tangzhiqiangh** [aws/amazon-cloudwatch-agent#1007]
Software package download

`wget https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb`

amazon-cloudwatch-agent version

`dpkg: version 1.300032.2b361-1 of amazon-cloudwatch-agent already installed, skipping`

Run the installation command

`sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m onPremise -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json`

`processing amazon-cloudwatch-agent 2024/01/08 09:45:20 E! Failed to open Common Config: open /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml: no such file or directory`

No errors occurred while installing the software. There is only an empty directory amazon-cloudwatch-agent.d in the etc directory. After manually editing the configuration file amazon-cloudwatch-agent.json and starting the agent, an error is reported but there is no "/opt/aws/amazon-cloudwatch-agent/etc/common-config.toml" ” Is it a problem with this version?

**Comment by jefchien** [comment]
If the `common-config.toml` file was deleted, running `sudo dpkg -i -E ./amazon-cloudwatch-agent.deb` will not recreate it. You will need to do a fresh re-install (`sudo dpkg -P amazon-cloudwatch-agent` to purge the package before reinstalling). Would recommend moving your JSON configuration file outside of the agent directories as well.
