### ISSUE TITLE
build: The date --iso-8601=seconds option does not work on macOS

### ISSUE THREAD

**Issue by at15** [aws/amazon-cloudwatch-agent#101]
It's just a minor issue for people using macOS.

Mac is not using the GNU version of coreutils, See https://stackoverflow.com/questions/7216358/date-command-on-os-x-doesnt-have-iso-8601-i-option

In the Makefile

```
BUILD = $(shell date --iso-8601=seconds)
LDFLAGS = -s -w
LDFLAGS +=  -X github.com/aws/amazon-cloudwatch-agent/cfg/agentinfo.VersionStr=${VERSION}
LDFLAGS +=  -X github.com/aws/amazon-cloudwatch-agent/cfg/agentinfo.BuildStr=${BUILD}
```

Example output

```
$ make build

date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

And I think it might be better to use [Simply expanded variables](https://www.gnu.org/software/make/manual/html_node/Flavors.html#Flavors) `BUILD := $(shell date --iso-8601=seconds)` so all the binaries have the same `BuildStr`

btw: There is no [GitHub Issue Templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by haojhcwa** [comment]
Thank you for reporting this issue. We are also investigating on porting the agent to MacOS in the moment. Apart from the issue with the makefile, we realize to get CPU and Memory metrics on MacOS, we have to use CGO to compile the agent on MacOS environment, reason being the underlying gopsutil only works when CGO is used and getting those metrics from Mach kernel of MacOS.
We will update this issue soon.
