### ISSUE TITLE
local script failed to redirect to cw log even when it's created

### ISSUE THREAD

**Issue by wliew99** [aws/amazon-cloudwatch-agent#1017]
**Describe the bug**
On a local script that uses aws to perform some tasks, we want to have all console.log to sent to a cloudwatch log group and stream that the script create.  The create went through find with no error but upon the first console.log, we are getting the log stream does not exist.

**Steps to reproduce**

first line of script run"
```
await initLogGroups();
console.log("hello") 

```
we then got failure with the error/stack trace below
```
async function logToCloudWatchAndConsole(
	level: string,
	args: any[],
	originalConsoleMethod: (...args: any[]) => void
) {
	originalConsoleMethod(...args); // Log to console

	// Log to CloudWatch
	const params = {
		logGroupName,
		logStreamName,
		logEvents: [
			{
				timestamp: Date.now(),
				message: `[${level}] ${args.join(" ")}`,
			},
		],
		sequenceToken,
	};

	const command = new PutLogEventsCommand(params);
	const response = await cwLogs.send(command);
	sequenceToken = response.nextSequenceToken; // Update sequence token for next log
}

const logGroupName = "/me/myloggroup";
const logStreamName = `local-run-${Date.now()}`; // Unique log stream name for each run
const cwLogs = new CloudWatchLogsClient({
	region: "us-west-2",
});
let sequenceToken: any;

async function initLogGroups() {
	try {
		console.log(`initLogGroups...`);
		await cwLogs.send(new CreateLogGroupCommand({ logGroupName }));
		console.log(`👍 DONE creating log group ${logGroupName}`);
		await cwLogs.send(
			new CreateLogStreamCommand({ logGroupName, logStreamName })
		);
		console.log(`👍 DONE creating log stream ${logStreamName}`);
	} catch (error) {
		if (
			error instanceof Error &&
			error.name !== "ResourceAlreadyExistsException"
		) {
			throw error;
		}
		// Log group already exists, no action needed
	}

	// Create a new log stream
	const originalConsoleLog = console.log;
	console.log = async (...args) => {
		await logToCloudWatchAndConsole("INFO", args, originalConsoleLog);
	};
}
```
**What did you expect to see?**
able to see my logs in aws dashboard based on what i console.log in my script
the cw log group was created i confirm in the cloud but no stream.

**What did you see instead?**

C:\Users\me\myproject\mysubfolder\node_modules\@aws-sdk\client-cloudwatch-logs\dist-cjs\protocols\Aws_json1_1.js:3624
    const exception = new models_0_1.ResourceNotFoundException({
                      ^
ResourceNotFoundException: The specified log stream does not exist.
    at de_ResourceNotFoundExceptionRes (C:\Users\me\myproject\mysubfolder\node_modules\@aws-sdk\client-cloudwatch-logs\dist-cjs\protocols\Aws_json1_1.js:3624:23)
    at de_PutLogEventsCommandError (C:\Users\me\myproject\mysubfolder\node_modules\@aws-sdk\client-cloudwatch-logs\dist-cjs\protocols\Aws_json1_1.js:2932:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\me\myproject\mysubfolder\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async C:\Users\me\myproject\mysubfolder\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20

**What version did you use?**
aws-sdk for javascript v3
"@aws-sdk/client-cloudwatch": "^3.485.0",
"@aws-sdk/client-cloudwatch-logs": "^3.485.0",

**What config did you use?**
region = us-west-2

**Environment**
windows

**Additional context**

**Comment by okankoAMZ** [comment]
Hello, 
This is related to the aws-sdk not cloudwatch agent. You can find more information here: [AWS-SDK-JS](https://github.com/aws/aws-sdk-js) and create a issue there using this [link](https://github.com/aws/aws-sdk-js/issues/new/choose)
