### ISSUE TITLE
Custom log collection does not implement a collection interval

### ISSUE THREAD

**Issue by appleoddity** [aws/amazon-cloudwatch-agent#102]
I discovered today that the Amazon Cloud Watch Agent is continuously pulling custom log files causing sustained CPU usage on our AWS servers. Shouldn't the agent pull logs only at each collection interval? Instead, I see it constant as if it is stuck in an endless loop.

In cases where we are collecting IISLogs, and IIS has generated tens of thousands of log files in different directories, this causes the Cloud Watch Agent to produce sustained, high CPU usage as it is constantly perform a recursive directory listing and reading the most recent files. This can be seen in process monitor and it doesn't matter what log files are specified.

Here is am example config file: (But, I've confirmed it does not matter what log files are specified, even if it is a single file)
`{
	"logs": {
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "D:\\inetpub\\logs\\LogFiles\\**.log",
						"log_group_name": "IISLogs",
						"log_stream_name": "{instance_id}",
						"timezone":"UTC",
						"timestamp_format":"%Y-%m-%d %H:%M:%S"
					}
				]
			}
		}
	}
}`

Even if I add a metrics_collection_interval it ignores it.

Looking back in our cloudwatch metrics, it appears this problem has been occurring for a long time - at least several months.
Agent Version 1.247345.34

**Comment by haojhcwa** [comment]
Hi appleoddity,

Thank you for reporting this issue. This has been a known behavior of the agent, currently the agent would scan for new log files matching the pattern every second. The reason we are not making this period bigger is we have to balance between the potential loss or delay of logs going to the system and the cpu used by scanning for new logs. And we realize in most of the cases when customers facing high CPU usage is either having a inaccurate configuration or could find a way to make the configuration more specific thus reduce the CPU consumption. But if we modified polling period, it is a behavior change that could affect customer experience or even loss of logs for some edge cases like extreme high frequency rotation of logs.

The recursive behavior is only triggered when the pattern contains the SuperMeta "**" pattern, see code [here](https://github.com/aws/amazon-cloudwatch-agent/blob/39d84b8e3f5215a3e6d880b54a88e63a692ecd64/plugins/inputs/logfile/globpath/globpath.go#L76). And in most of the cases, the customer is only interested in 1 or 2 levels of special directory for the logs, modifying the pattern into multiple entries of normal "*" meta match pattern usually solves the problem.

With that being said, we do agree this is a short coming of the current agent, and there definitely room to improve, we would like to gather as much info as possible before propose a design that could optimize this process.

In fact, file globing is quite a common go problem that in the latest go language proposal of io.fs package, there is a special section talking about it and about its efficiency.

**Comment by appleoddity** [comment]
Thank you for the follow up.

It would seem that the best solution for this is to let the consumer decide. Expand the json schema and allow for a Collection_Interval for each custom log entry.

Breaking the Super wildcard down in to a bunch of regular wildcard entries is not possible. That is not how IIS logs. IIS creates a separate numbered log folder for each site automatically. We apply the cloudwatch configuration json uniformly across instances using an AWS Systems Manager document and parameter store. We will never know exactly what log folders are present in IIS on each instance, and in our case we have dozens of them on different instances. We are also limited to 8KB in the parameter store and can not waste space with fruitless entries in hopes that we will cover them all.

One possible mitigation is to allow the CloudWatch agent to remove old IIS logs so that the directory structure is less complex. However, I tested this and there are two problems. The agent is constantly battling with IIS, deleting the current daily log, while IIS re-creates it. In addition, the agent does not remove anything except the current daily log and leaves behind all the older daily logs which are the ones it is actually supposed to be clearing out. There is an additional bug that the CloudWatch agent is duplicating every log entry multiple times in CloudWatch if this feature is turned on. I assume I should create a separate bug report for that? Basically, this feature is broken in multiple ways.

**Comment by appleoddity** [comment]
Are there any documents on compiling the agent from source code? I'm not familiar with GO. But, I'm assuming there is an IDE and method to compiling the code from scratch. If that were the case, I may branch the code and work on solving some of these problems, but this is not my primary line of work. However, I'm always happy to contribute to the community.

**Comment by haojhcwa** [comment]
Hi appleoddity,

The instructions on how to build the agent can be found from the README.md:
https://github.com/aws/amazon-cloudwatch-agent/#building-and-running-from-source

All you need is correctly install [`go`](https://golang.org) language (1.13 or later), and have `make` utility available.

If you do not want to use `make` or unable to install make, you can find the go command that actually build the agent here:
https://github.com/aws/amazon-cloudwatch-agent/blob/master/Makefile#L30-L32

However, that would require you to have a better understanding of the agent and replace some of the variables used by the command.

**Comment by appleoddity** [comment]
@jennbergs I'm not sure of the status of current agent versions. However, we implemented a scheduled task to keep files cleaned out of our IIS logs specifically. The CPU burden is when there is an excessive amount of log files being scanned within the monitored directories.

The scheduled task runs the following powershell scripts (with parameters):
```
# Recursively deletes files older than $MaxAge days in $Folder

param (
    [int]$MaxAge = 30,
    [Parameter(Mandatory=$true)]
    [string]$Folder
)

get-childitem -Path $Folder -Recurse -File | Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-$MaxAge)} | Remove-Item -Force
```

Task - Start a program:
`powershell.exe -ExecutionPolicy Bypass "\\<shared-network-location\CleanFolder.ps1" -Folder 'D:\inetpub\logs\LogFiles' -MaxAge 7"`

Task - Trigger:
Run weekly on Sunday

**Comment by jhnlsn** [comment]
The agent does not perform any cleanup of log files itself, which means if you are using a wildcard search for log files, the agent will keep scanning all files found until they are removed.  There is a cpu cost per file watched.  Hope this helps.
