### ISSUE TITLE
The CloudWatch Agent requires additional configuration to use IAM Roles for Service Accounts (IRSA) or Pod Identity

### ISSUE THREAD

**Issue by AaronFriel** [aws/amazon-cloudwatch-agent#1085]
This issue is duplicated for visibility from:
- https://github.com/aws/amazon-cloudwatch-agent-operator/issues/119

Users may wish to run the CloudWatch Agent using pod-based IAM roles, using the IRSA or EKS Pod Identities technologies. Recently (PR below) this was enabled when an environment variable is set on the agent pod, `RUN_WITH_IRSA=true`, and this enables the agent to utilize the default provider chain for AWS authentication.

But the managed operator (EKS Addon) doesn't provide any mechanism to set this currently, further, it seems a bit strange that a user would have to **opt in** to working identity IAM, when valid IRSA/EKS Pod Identity chains are present.

## Background

CloudWatch Agent PR:
- https://github.com/aws/amazon-cloudwatch-agent/pull/682/files

# Expected behavior

When deployed by the EKS Addon, the AWS CloudWatch Agent should work by default with pod-based IAM.

# Actual behavior

The agent fails, and there is no knob available to users to ensure the agent works.

# Proposal

Either of these solutions would address this:
* The Addon and Operator should permit an additional configuration, to merge either individual env vars or arbitrary config into the `AmazonCloudWatchAgent` custom resource
* The Agent's configuration file, `cwagentconfig.json`, which is managed by the add-on should accept a configuration key to enable the RUN_WITH_IRSA mode.
* The Agent should detect available authentication methods, and prefer a successful authentication via default chain rather than bespoke authentication methods.

**Comment by jefchien** [comment]
Will track this in the operator issue you have open.
