### ISSUE TITLE
https://github.com/aws/amazon-cloudwatch-agent/releases shows v1.300034.0 but that is not current

### ISSUE THREAD

**Issue by JoeBrunsTR** [aws/amazon-cloudwatch-agent#1178]
https://github.com/aws/amazon-cloudwatch-agent/releases shows v1.300034.0 but that is not current

I think v1.300039.0 is

When is someone going to update this?

**Comment by jefchien** [comment]
Hi @JoeBrunsTR, thanks for bringing this to our attention. I've updated the release page so we're caught up with the latest release and all the releases in between. We'll make sure to keep this up to date going forward.
