### ISSUE TITLE
Globpath logic error

### ISSUE THREAD

**Issue by murphm8** [aws/amazon-cloudwatch-agent#121]
https://github.com/aws/amazon-cloudwatch-agent/blob/e770cd8fbdded909034a06550e8d2e40ebbf43fb/plugins/inputs/logfile/globpath/globpath.go#L32-L34

This code should be `!out.hasMeta && !out.hasSuperMeta` based on the comment that it should skip if there are no meta characters. I'm not sure if this really affects anything since the `Match()` method would still react correctly.

**Comment by yimuniao** [comment]
The logic came from https://github.com/influxdata/telegraf/blob/master/internal/globpath/globpath.go#L29

Yes, you are correct, the logic seems incorrect. I will check if I can create a pull request to upstream. 


Thanks a lot
