### ISSUE TITLE
make release of the source code not generating rpm or deb files

### ISSUE THREAD

**Issue by maheshtnl2009** [aws/amazon-cloudwatch-agent#123]
when pulled the code on aws ec2 machine , make build  executed without issues but no rpm deb files are generated in the folders as mentioned in the read me files.  after executing the make release resulted in failure , some of the steps were failed as shown below & machine details were provided after the fail steps

FAIL  github.com/aws/amazon-cloudwatch-agent/awscsm/csm [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/awscsm/sdkmetricsdataplane [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/cfg/aws [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/cfg/commonconfig [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/cmd/amazon-cloudwatch-agent-config-wizard [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/cmd/config-translator [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/internal/ecsservicediscovery [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/internal/k8sCommon/k8sclient [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/internal/k8sCommon/k8sutil [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/internal/k8sCommon/kubeletutil [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/internal/publisher [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/internal/structuredlogscommon [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/logger [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/metric/distribution/regular [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/metric/distribution/seh1 [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/awscsm [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/cadvisor/extractors [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/demo [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/k8sapiserver [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/logfile [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/logfile/globpath [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/prometheus_scraper [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/statsd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/inputs/statsd/graphite [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/outputs/awscsm [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/outputs/awscsm/providers [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/outputs/cloudwatch [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/outputs/cloudwatchlogs [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/parsers/awscsm [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/parsers/emf [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/processors/delta [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/processors/ec2tagger [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/processors/ecsdecorator [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/processors/emfProcessor [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/processors/k8sdecorator/stores [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/plugins/processors/k8sdecorator/structuredlogsadapter [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/profiler [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config/logs [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config/metric [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config/metric/collectd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config/metric/linux [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config/metric/statsd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/data/config/metric/windows [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/agentconfig [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/basicInfo [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/collectd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/defaultConfig [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/migration [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/migration/linux [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/migration/windows [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/question [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/question/events [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/question/logs [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/question/metrics [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/serialization [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/ssm [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/processors/statsd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/tool/util [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/config [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/jsonconfig [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/toenvconfig [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/totomlconfig [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/agent [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/csm [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/globaltags [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs/logs_collected/files/collect_list [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs/logs_collected/windows_events [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs/logs_collected/windows_events/collect_list [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs/metrics_collected [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs/metrics_collected/emf [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/logs/metrics_collected/prometheus/ecsservicediscovery/taskdefinition [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/append_dimensions [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metric_decoration [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/agentInternal [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/collectd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/cpu [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/disk [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/diskio [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/ethtool [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/mem [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/net [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/netstat [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/processes [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/procstat [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/statsd [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/metrics_collect/swap [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/rollup_dimensions [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/util [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/translate/util [build failed]
FAIL  github.com/aws/amazon-cloudwatch-agent/translator/util [build failed]
make: *** [test] Error 2

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Comment by yimuniao** [comment]
What is the issue? You did not paste the error log.

**Comment by maheshtnl2009** [comment]
> What is the issue? You did not paste the error log.
installation not working as mentioned in the document.
 I pasted all the errors that I have encountered. please check..

**Comment by yimuniao** [comment]
I failed to reproduce this issue on my own ec2 instance. Did you setup go language tools? could you describe the detail steps what you did?

**Comment by yimuniao** [comment]
Reproduced this issue when launch a new ec2 instance. I will dig it. 
Thanks

**Comment by yimuniao** [comment]
Could you try to run "sudo yum install gcc" to install gcc first? and then "make test"?

**Comment by maheshtnl2009** [comment]
installed gcc and executed make test , make build, make release .Errors gone but still I dont see any rpm or deb files generated 

make release ending with this error below:

ok    github.com/aws/amazon-cloudwatch-agent/translator/translate/util  0.005s
=== RUN   TestSetWithSameKeyIfFound
--- PASS: TestSetWithSameKeyIfFound (0.00s)
=== RUN   TestSetWithCustomizedKeyIfFound
--- PASS: TestSetWithCustomizedKeyIfFound (0.00s)
PASS
ok    github.com/aws/amazon-cloudwatch-agent/translator/util   0.005s
?     github.com/aws/amazon-cloudwatch-agent/translator/util/ec2util    [no test files]
?     github.com/aws/amazon-cloudwatch-agent/translator/util/ecsutil    [no test files]
?     github.com/aws/amazon-cloudwatch-agent/translator/util/httpclient [no test files]
FAIL
make: *** [test] Error 1

**Comment by yimuniao** [comment]
I guess some unittest is unstable. could you try to install rpm-build package and then try to build again?

`sudo yum install -y rpm-build`
`make release`
