### ISSUE TITLE
Support for creating config.json file from system local path 

### ISSUE THREAD

**Issue by maheshtnl2009** [aws/amazon-cloudwatch-agent#124]
after installing the repository in aws linux  machine , there will be no config.json file created in the location /opt/aws/amazon-cloudwatch-agent/bin..

I would like to request for running  some command so that i can pass the file location as the argument , so the config .json file will be created in the required location ..

**Comment by yimuniao** [comment]
You can create config.json in any directory manually. then you can run /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl command to import config.json  to  /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/

Could you describe what commands did you run?

**Comment by maheshtnl2009** [comment]
yes , thanks for the info . it resolved my question ..

How can we generate the multiple namespaces from a single server/machine/instance ..

"namespace":"CPUMetrics" --CPU related metrics 
"namespace":"RAMMetrics" --RAM related metrics

**Comment by yimuniao** [comment]
No, you can not do it. only one namespace is supported.

**Comment by maheshtnl2009** [comment]
can we provide atleast muliple submaes in a single name space
namespace : metrics subname:CPU
namespace : metrics subname:RAM

**Comment by yimuniao** [comment]
I suggest you add different dimension for CPU and RAM metrics. Refer to append_dimensions in https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html

**Comment by yimuniao** [comment]
long time no response, close it.
