### ISSUE TITLE
adding new file in create rpm sh 

### ISSUE THREAD

**Issue by maheshtnl2009** [aws/amazon-cloudwatch-agent#129]
I have added new file json to the script  and executed make build .. build went to no success with the error as below :

check_secrets failed
make: *** [check_secrets] Error 1

**Comment by mxiamxia** [comment]
Can you please share your new json file? It most likely your new changes is failed on the following regex check.

```
check_secrets::
	if grep --exclude-dir=build --exclude-dir=vendor -E "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}|(\"|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)(\"|')?\\s*(:|=>|=)\\s*(\"|')?[A-Za-z0-9/\\+=]{40}(\"|')?" -Rn .; then echo "check_secrets failed"; exit 1; fi;
```

**Comment by maheshtnl2009** [comment]
touch $(BUILD_SPACE)/private/linux/amd64/rpm/amazon-cloudwatch-agent-pre-pkg/config.json

this is the json file name that Iam adding to our make file in package-prepare-rpm:  section of Makefile.

As this is a new file being created, i think we need to add regex check on this file. How can we add regex check on this new file.

data in the file can be anything like this:
{
        "agent": {
                "metrics_collection_interval": 60,
                "run_as_user": "root"
        },
        "metrics": {
                "namespace":"Dev/ProdCpuMetrics",
                "append_dimensions": {
                        "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
                        "ImageId": "${aws:ImageId}",
                        "InstanceId": "${aws:InstanceId}",
                        "InstanceType": "${aws:InstanceType}"
                },
                "metrics_collected": {
                         "cpu": {
                                "measurement": [
                                        "cpu_usage_idle",
                                        "cpu_usage_iowait",
                                        "cpu_usage_user",
                                        "cpu_usage_system"
                                ],
                                  "metrics_collection_interval": 60,
                                "resources": [
                                        "*"
                                ],
                                "totalcpu": false
                        }                      
                }
        }
}

**Comment by yimuniao** [comment]
Are you going to generate the configuration file dynamically to $(BUILD_SPACE)/private?

If it is not in the source codes, why do you want to check it?

**Comment by maheshtnl2009** [comment]
I need to add those lines to create_rpm.sh script , when I do any
modification to this shell script file, with respect to script file  it is
failing with the error as check_errors failed.

I need to do some thing  to make this check_errors state as passed so that
the rest of the build process  and release process will go to success.

this is not related to the new file added and this is related to the
modifications made to the existing create rpm script and this is part of
the src code..

Regards
Mahesh.

**Comment by yimuniao** [comment]
I think you modified some source codes and leaked the credentials into the source file.

Could you run following command? it will show which file contains the credentials, you can remove the credentials.

`grep --exclude-dir=build --exclude-dir=vendor -E "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}|(\"|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)(\"|')?\\s*(:|=>|=)\\s*(\"|')?[A-Za-z0-9/\\+=]{40}(\"|')?" -Rn .`

**Comment by yimuniao** [comment]
Long time no response, close it.
