### ISSUE TITLE
BUG: Unnecessary error in logs for prometheus metric scraping

### ISSUE THREAD

**Issue by lonnix** [aws/amazon-cloudwatch-agent#138]
I have cloudwatch-agent setup to scrape Prometheus metrics from my pods, however only one of the pods actually has an endpoint exposing those metrics. I am getting everything showing up in Cloudwatch correctly, but the logfiles for cloudwatch-agent are filling up very quickly with 
```
2020-12-08T17:56:40Z D! receive metric batch with 0 prometheus metrics
2020-12-08T17:56:40Z E! Failed to get Job Name and Instance ID from Prometheus metrics.
```

With debug mode disabled only the 2nd line shows up, but it shows up a few times every second so that's about all you see in the logs.

Is this as simple as adding a check for `count > 0` somewhere before decorating? I don't mind making a PR if that is all that is needed.

**Comment by lonnix** [comment]
In kiali I am seeing around 87% of my outgoing request getting 5XX errors, most being 503s. I am not sure if this is related to the OP, but as much as it is happening across all pods it seems it might be.

My config has this at the top of `relabel_configs`
```
- source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  action: keep
  regex: true
```

I would expect that anything without `prometheus.io/scrape: true` as an annotation is ignored and does not write anything to logs and does not return a 5XX, but that does not seem to be the case

**Comment by pxaws** [comment]
I don't think it is good to hide this error message: "E! Failed to get Job Name and Instance ID from Prometheus metrics". It shows up when prometheus fails to scrape the metrics. It seems like your prometheus config contains targets that can't be scraped. To get rid of the error message, you can try to remove those targets.

**Comment by lonnix** [comment]
I would like to have a more open config so that I don't have to adjust it every time a developer adds an endpoint since I don't want them all to have access to the amazon-cloudwatch namespace and a shared config file, hence it scanning all apps. 

What would be the solution if I went config by config? I have 100 namespaces and 30 developers, so having a centralized prometheus configuration seems hard to manage in that case.

**Comment by pxaws** [comment]
>Is there a way of distinguishing between "had an error while scraping" and "successfully scraped but found no targets"?

There seems to be no way to distinguish the two cases for cloudwatch agent. We relies on prometheus lib to do the scraping for us. I don't see any api are provided from prometheus lib for that.

>What would be the solution if I went config by config? I have 100 namespaces and 30 developers, so having a centralized prometheus configuration seems hard to manage in that case.

Can you let the developers to manage their own cloudwatch agent separately? They could use a different namespaces for their cloudwatch agent instances. Having a centralized way to scrape all the targets from different teams doesn't seems like a scalable way.

**Comment by lonnix** [comment]
Closing this issue because it looks like there isn't a programmable solution.
