### ISSUE TITLE
I want to get the metrics data through API

### ISSUE THREAD

**Issue by wangfan0524** [aws/amazon-cloudwatch-agent#142]
I've started cloudwatch agent，and I configured port 8125,then what path can I get the data of metrics from my browser。

**Comment by yimuniao** [comment]
Do you mean you do not know how to find the metrics on cloudwatch console, right?
If yes, I think you know what metrics you send to port 8125, then you can search the metrics name on cloudwatch console.

**Comment by pingleig** [comment]
@wangfan0524 any update on the issue? btw: cwagent itself does not ship with a builtin database/dashboard so you have to give it aws credential and send the data to cloudwatch API.
