### ISSUE TITLE
Private VPCE:  Cloudwatch agent POSTs failing with TLS/CN mismatch error

### ISSUE THREAD

**Issue by krwags** [aws/amazon-cloudwatch-agent#146]
Hello -

We are running this agent to make private connections through VPCE with Cloudwatch service.  We configured the "endpoint_override" values and it's definitely attempting to POST data to the endpoint.

The problem is that the CWAgent log says:

RequestError: send request failed
caused by: Post "https://vpce-1234567890kdjfdkjf.logs.us-gov-west-1.vpce.amazonaws.com/": x509: certificate is valid for logs.us-gov-west-1.amazonaws.com, logs-fips.us-gov-west-1.amazon.com, not vpce-1234567890kdjfdkjf.logs.us-gov-west-1.vpce.amazonaws.com

Is there a way to relax TLS verification?  maybe some insecure_skip_verify setting somplace?

Thanks,
Keith

**Comment by pingleig** [comment]
Based on the code, we are using the default http client with default tls transport in aws go sdk, so there is no config for the insecure option.

https://github.com/aws/amazon-cloudwatch-agent/blob/master/plugins/outputs/cloudwatchlogs/cloudwatchlogs.go#L111-L116

```go
	client := cloudwatchlogs.New(
		credentialConfig.Credentials(),
		&aws.Config{
			Endpoint: aws.String(c.EndpointOverride),
		},
	)
```

I feel it's a valid  feature request to allow users to configure it, as long as they are aware of the potential problem of those configs.

I will bring it up to the team, but it is likely going to be bundled with other bigger feature/fixes, so there is no clear timeline...
If you do need it right away, the easiest way is to update those lines to pass a http client with transport that skips tls verify, and [build the deb/docker image from source](https://github.com/aws/amazon-cloudwatch-agent#building-and-running-from-source)

**Comment by jhnlsn** [comment]
To close this one out for anyone that needs this info in the future.  You need to set the `AWS_CA_BUNDLE` environment variable with your private CA bundle.  See for more information: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
