### ISSUE TITLE
Release 1.247347.0b250208 terminates unexpectedly causing CPU load

### ISSUE THREAD

**Issue by andrewlorien** [aws/amazon-cloudwatch-agent#155]
I deployed an EC2 Windows instance this week, including https://s3.amazonaws.com/amazoncloudwatch-agent/windows/amd64/latest/amazon-cloudwatch-agent.msi 
The instance started up OK, but CPU was running between 40% and 80% which caused our auto scale group to scale up to the maximum.  The Windows system logs include thousands of events like

```
The CWAgent Otel Collector service terminated unexpectedly. It has done this 11646 time(s). The following corrective action will be taken in 2000 milliseconds: Restart the service.
The CWAgent Otel Collector service terminated with the following error: An exception occurred in the service when handling the control request.
The CWAgent Otel Collector service entered the stopped state.
```
I have these log entries in CloudWatch logs, so that agent and connector are working correctly.

All our other environments are running CWAGENT_VERSION 1.247346.1b249759 or a previous one, and none have this problem (I see from the release notes that the Otel collector has only been added with this release).  This is Windows 2019 built from the [latest CIS hardened AMI](https://www.cisecurity.org/cis-hardened-images/amazon/) running .Net classic with all windows and dotNet patches up to date.

The full event logs:
```
<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Service Control Manager' Guid='{555908d1-a6d7-4695-8e1e-26931d2012f4}' EventSourceName='Service Control Manager'/><EventID Qualifiers='49152'>7023</EventID><Version>0</Version><Level>2</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x8080000000000000</Keywords><TimeCreated SystemTime='2021-01-05T08:37:08.735977500Z'/><EventRecordID>86168</EventRecordID><Correlation/><Execution ProcessID='608' ThreadID='2640'/><Channel>System</Channel><Computer>EC2AMAZ-XXXXXXX</Computer><Security/></System><EventData><Data Name='param1'>CWAgent Otel Collector</Data><Data Name='param2'>%%1064</Data><Binary>430057004100670065006E0074004F00740065006C0043006F006C006C006500630074006F0072000000</Binary></EventData><RenderingInfo Culture='en-US'><Message>The CWAgent Otel Collector service terminated with the following error: An exception occurred in the service when handling the control request.</Message><Level>Error</Level><Task></Task><Opcode></Opcode><Channel></Channel><Provider>Microsoft-Windows-Service Control Manager</Provider><Keywords><Keyword>Classic</Keyword></Keywords></RenderingInfo></Event>	
<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Service Control Manager' Guid='{555908d1-a6d7-4695-8e1e-26931d2012f4}' EventSourceName='Service Control Manager'/><EventID Qualifiers='49152'>7031</EventID><Version>0</Version><Level>2</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x8080000000000000</Keywords><TimeCreated SystemTime='2021-01-05T08:37:08.735977500Z'/><EventRecordID>86169</EventRecordID><Correlation/><Execution ProcessID='608' ThreadID='4220'/><Channel>System</Channel><Computer>EC2AMAZ-XXXXXXX</Computer><Security/></System><EventData><Data Name='param1'>CWAgent Otel Collector</Data><Data Name='param2'>11646</Data><Data Name='param3'>2000</Data><Data Name='param4'>1</Data><Data Name='param5'>Restart the service</Data><Binary>430057004100670065006E0074004F00740065006C0043006F006C006C006500630074006F0072000000</Binary></EventData><RenderingInfo Culture='en-US'><Message>The CWAgent Otel Collector service terminated unexpectedly. It has done this 11646 time(s). The following corrective action will be taken in 2000 milliseconds: Restart the service.</Message><Level>Error</Level><Task></Task><Opcode></Opcode><Channel></Channel><Provider>Microsoft-Windows-Service Control Manager</Provider><Keywords><Keyword>Classic</Keyword></Keywords></RenderingInfo></Event>	
<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Service Control Manager' Guid='{555908d1-a6d7-4695-8e1e-26931d2012f4}' EventSourceName='Service Control Manager'/><EventID Qualifiers='16384'>7036</EventID><Version>0</Version><Level>4</Level><Task>0</Task><Opcode>0</Opcode><Keywords>0x8080000000000000</Keywords><TimeCreated SystemTime='2021-01-05T08:37:08.735977500Z'/><EventRecordID>86167</EventRecordID><Correlation/><Execution ProcessID='608' ThreadID='2640'/><Channel>System</Channel><Computer>EC2AMAZ-XXXXXXX</Computer><Security/></System><EventData><Data Name='param1'>CWAgent Otel Collector</Data><Data Name='param2'>stopped</Data><Binary>430057004100670065006E0074004F00740065006C0043006F006C006C006500630074006F0072002F0031000000</Binary></EventData><RenderingInfo Culture='en-US'><Message>The CWAgent Otel Collector service entered the stopped state.</Message><Level>Information</Level><Task></Task><Opcode></Opcode><Channel></Channel><Provider>Microsoft-Windows-Service Control Manager</Provider><Keywords><Keyword>Classic</Keyword></Keywords></RenderingInfo></Event>
```

**Comment by yimuniao** [comment]
Did you try to start CWAgent Otel Collector? normally, after it will not start automatically after installation. Which command did you run to start the  service?

**Comment by yimuniao** [comment]
If the configuration file`C:\ProgramData\Amazon\AmazonCloudWatchAgent\CWAgentOtelCollector\cwagent-otel-collector.yaml` does not exist, AOC service will keep restarting after you try to restart AOC or reboot the instances.

I suggest you run stop command, like ` C:\'Program Files'\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1 -a stop` after host rebooting each time.

**Comment by andrewlorien** [comment]
Thanks for the quick reply.   We start the installer with `start-process -FilePath 'msiexec.exe' -Wait -ArgumentList "/i c:\cfn\amazon-cloudwatch-agent.msi /qn"` , then write the C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\amazon-cloudwatch-agent.json file, then restart the agent with `powershell -Command "C:\\'Program Files'\\Amazon\\AmazonCloudWatchAgent\\amazon-cloudwatch-agent-ctl.ps1 -a stop` then `powershell -Command "C:\\'Program Files'\\Amazon\\AmazonCloudWatchAgent\\amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -c file:C:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\amazon-cloudwatch-agent.json -s`

We don't have an otel-collector file, because we didn't need one until this week, I'll add it and confirm here.  

This is likely to happen to every existing user of the cloudWatch agent. I suggest that instead of restarting the service every two seconds in the hope that the file might appear, the service simply shut down permanently with a message like "The configuration file was not found."

**Comment by yimuniao** [comment]
Did you reboot instance or bake the AMI after install MSI?

**Comment by andrewlorien** [comment]
After installing the CloudWatch MSI we do lots of other stuff including installing dotNet, then we reboot before we run CodeDeploy - and then it goes into service.  We're not baking AMIs, although the more trouble we have with windows updates and services the more we're considering it.

I've just copied the yaml file manually on one instance, and the CWAgentOtelCollector is running.  Adding that to the cfn script now.

**Comment by yimuniao** [comment]
Thanks for reporting this issue. I will follow up how to fix this issue permanently.

**Comment by yimuniao** [comment]
@andrewlorien could you help to confirm the CPU goes down after the fix?

**Comment by andrewlorien** [comment]
Here's an instance I started at 00:40UTC.  At 02:15 I copied the yaml file and confirmed that the agent wasn't restarting (there was no other activity on that server). CPU is down from a peak of 92% to around 10% (the Y axis is 0-100%)
![image](https://user-images.githubusercontent.com/10932833/103729119-cb579180-5033-11eb-890b-c7ec17b13d3d.png)

**Comment by andrewlorien** [comment]
Thanks for your help with this.
It looks like the /latest in S3 has reverted to 1.247346.1b249759 
But with this line after the msi has run, we're fine either way (i know, a dos command in 2021, what's the world coming to?)

**Comment by treyperrone-nasa** [comment]
> Did you reboot instance or bake the AMI after install MSI?

@yimuniao - Do you know of issues with cloudwatch and baked AMIs? I am hitting something similar when baking windows 2019 and when spinning up the AMI. cwatch 1.247347.6b250880

**Comment by pingleig** [comment]
It seems you are using the latest release, we did upgraded the bundled otel collector version in recent releases. Though we didn't change the logic for otel collector, do you see similar log of otel collector keep restarting?

**Comment by treyperrone-nasa** [comment]
> It seems you are using the latest release, we did upgraded the bundled otel collector version in recent releases. Though we didn't change the logic for otel collector, do you see similar log of otel collector keep restarting?

In this case I am using Hashi Packer to bake the AMI - it pipes over a default name toml + json config and service is started with win service (ansible). After a bunch of other things get installed I run a `C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule` and then let the AMI bake in the easy oven. 

After launching a new instance off of the baked AMI i figured the service would just start up and work but it does not. If i manually start it it starts working ok. I am likely messing up a step in the build process and/or missing something simple. I did find an error about `Cannot translate JSON config into TOML, ERROR is exit status 1`  the logs from 19th are the spun up packer instance. logs at end from 20th are instance i started today.  https://gist.github.com/treyperrone-nasa/4ed88954c9a03617ccf1ef367f25e792 

I'll re-check the docs in the AM after the morning cup of coffee 👍
