### ISSUE TITLE
[Feature Request] option to collect metrics immediately on startup

### ISSUE THREAD

**Issue by jedwards1211** [aws/amazon-cloudwatch-agent#161]
I'm using CloudFormation to create an EC2 Instance with CloudWatch Agent and a CloudWatch Alarm if the `disk_used_percent` is above a certain threshold, or data is missing (assuming that means the instance is hosed).

The alarm unfortunately triggers at first because there is a delay before CloudWatch Agent sends the first metrics.  I set `force_flush_interval` to 0 but it still appears to wait for the first `metrics_collection_interval` to elapse before collecting and sending the metrics, so in my `UserData` script I have to `sleep 70` before calling `cfn-signal` on the instance, so that the alarm doesn't get created until data is present.

On top of that, I only need a 5 minute data interval, so to avoid pointless wait during deployment I have to start the agent with a 1 minute interval, sleep, and then reconfigure the agent to use a 5 minute interval.

This has been tedious and time-consuming to set up.  I wish there were a config option to collect and send metrics immediately on startup, or at least the subset of metrics that can be collected instantaneously.

**Comment by wyTrivail** [comment]
@jedwards1211  yeah, this is a pain for us as well, while doing integration-test, we also have to wait for a while until the metric appears otherwise the alarms fail to be created.   

It might be great if CloudWatch Alarm can support a metric pulling feature with timeout while creating.

It would be hard for agent to send out the metrics immediately base on the current framework, and these data could be  inaccurate which would make the metric graph looks weird every time there is a new instance created.

**Comment by jhnlsn** [comment]
I believe the best place for a feature like this would be with the alarms service.  I don't think there is anything specifically that the agent can do in this case.

**Comment by jedwards1211** [comment]
@jhnlsn why should the agent not immediately send metrics on startup though?  Who would prefer to not have any metrics about a new instance until five minutes after it's started?  That's a long time to not have visibility into the performance of a new instance

edit - I forgot that the default interval is 1 minute.  Better, but still it's annoying to be in the dark for a long time on startup if we want a longer collection interval

**Comment by jedwards1211** [comment]
@wyTrivail 
> and these data could be inaccurate which would make the metric graph looks weird

Are you saying that the agent is actually aggregating multiple more frequent samples than that under the hood during each metrics collection interval?

If so I don't see any transparency about this in the documentation (not to mention an option to control a smaller sampling interval than the collection interval), I had assumed it just collects instantaneous values.
