### ISSUE TITLE
[Feature Request] Ability to ignore kubernetes resources by annotation

### ISSUE THREAD

**Issue by darkhelmet** [aws/amazon-cloudwatch-agent#162]
I have a few things that I'd really like to ignore in my cluster that runs Jenkins/CI jobs...I don't need CPU metrics and junk for every builder pod that comes along. Since CW charges by the metric...that gets expensive.

I know my way around Go, if somebody wants to point me at the right spot I'd be happy to develop and test a change on our CI cluster. I'm looking at a number of different spots in the code right now, but I think I should be catching the pod as early as possible in the pipeline. Maybe right at the `Watch` but I'm just looking to see if I can figure out a field selector that will work...

**Comment by darkhelmet** [comment]
Maybe just the `transformFuncPod` function above the `createPodListWatch`. Looks like I should be able to return an error from the transform func and it'll spit out some errors but will probably ignore things.

**Comment by mxiamxia** [comment]
Hi @darkhelmet, how do you setup CWAgent in your Kubernetes? are you using CWAgent container insight?

**Comment by darkhelmet** [comment]
I use the resources linked to via https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-metrics.html but I use Terraform to install them so I've converted them to terraform kubernetes provider resources.

**Comment by pxaws** [comment]
It looks like if you add some filtering for those pods that you don't want to track: https://github.com/aws/amazon-cloudwatch-agent/blob/d4310b74f917dc3b8773db81f5205e646ac1c674/internal/k8sCommon/k8sclient/obj_store.go#L50-L54 then those pod info will not be written into cache. In this way, you can should be able to get rid of those unwanted metrics.

**Comment by darkhelmet** [comment]
I actually started a PR for this that we've been running in production for a bit now #163

**Comment by darkhelmet** [comment]
Closed in #163
