### ISSUE TITLE
Monitor Windows event viewer debug trace logs

### ISSUE THREAD

**Issue by gregorianza** [aws/amazon-cloudwatch-agent#176]
I'm using Microsoft AD FS and enabled trace logging as per https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging#trace-log however CWAgent is unable to monitor this event log (AD FS Tracing/Debug). I'm not sure if its related to the type of file (%SystemRoot%\System32\Winevt\Logs\AD FS Tracing%4Debug.etl) or the structure of the log that CWAgent doesn't understand. When enabling debugging in the agent there is no hint of any issues, no hint either that the agent is failing/able to read this event log and additionally the CW log group does not get created. Monitoring a regular event log works fine, config.json included below. Any ideas here? 

![image](https://user-images.githubusercontent.com/79209212/108219077-07573980-713e-11eb-8829-7aa86a46033c.png)

{
"agent": {
   "debug": true
  },
	"logs": {
		"logs_collected": {
			"windows_events": {
				"collect_list": [
					{
						"event_format": "xml",
						"event_levels": [
							"WARNING",
							"ERROR",
							"CRITICAL",
							"INFORMATION",
							"VERBOSE"
						],
						"event_name": "AD FS Tracing/Debug",  <<<< not monitoring any logs
						"log_group_name": "{instance_id}",
						"log_stream_name": "Trace-debug"
					},
					{
						"event_format": "xml",
						"event_levels": [
							"WARNING",
							"ERROR",
							"CRITICAL",
							"INFORMATION",
							"VERBOSE"
						],
						"event_name": "AD FS/Admin",  <<<< successfully monitoring logs
						"log_group_name": "{instance_id}",
						"log_stream_name": "ADFS-admin"
					}
				]
			}
		}
	}
}

**Comment by shaochengwang** [comment]
Hi, I see you turned on the `debug` flag. Could you please also provide the `amazon-cloudwatch-agent.log` with the debug information?
Thanks

**Comment by gregorianza** [comment]
[amazon-cloudwatch-agent.log](https://github.com/aws/amazon-cloudwatch-agent/files/6004842/amazon-cloudwatch-agent.log)

amazon-cloudwatch-agent.log attached. Refer from 2021-02-17T10:14:45Z. From this time I performed service restarts of AD FS and could see the new events being written to the respective event logs by checking the event viewer in Windows. 

2021-02-17T10:15:27Z log events were monitored from AD FS/Admin event log but nothing from AD FS Tracing/Debug. Same can be seen later on through the agent log. 

From 2021-02-17T11:25:14Z I reverted my config.json to only monitor the System event log.

**Comment by pxaws** [comment]
Based on this doc https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging#trace-log, the trace log is not enabled by default (and the admin log is enabled by default). Could you check if you have the trace log enabled successfully or not?

**Comment by gregorianza** [comment]
Yes the trace debug log is successfully enabled, below is screenshot showing the events; 

![image](https://user-images.githubusercontent.com/79209212/110575531-aaacd480-8167-11eb-8e7d-ece57c3f5fab.png)

**Comment by adam-mateen** [comment]
I built from master-branch and do not see this issue.
I also tested the official `1.247349.0` release. 
I tested on a windows server 2019 EC2 instance.
I used this Agent config:
```
{
	"agent": {
		"debug": true
	},
	"logs": {
		"logs_collected": {
			"windows_events": {
				"collect_list": [
					{
						"event_format": "text",
						"event_levels": [
							"INFORMATION",
							"WARNING",
							"ERROR",
							"CRITICAL"
						],
						"event_name": "Application",
						"log_group_name": "Application",
						"log_stream_name": "{instance_id}"
					},
					{
						"event_format": "text",
						"event_levels": [
							"INFORMATION",
							"WARNING",
							"ERROR",
							"CRITICAL"
						],
						"event_name": "AD FS Tracing/Debug",
						"log_group_name": "ADFS_DEBUG",
						"log_stream_name": "{instance_id}"
					}
				]
			}
		}
	}
}
```

I used this PowerShell script to write some events to that eventlog:
```
$ename = "AD FS Tracing/Debug"
$src = "Sheep"
$msg = "Beep Beep "

if ([System.Diagnostics.EventLog]::SourceExists($src) -eq $False) {
	New-EventLog -LogName $ename -Source $src
}

$i = 0
while (1) {
	$cur_msg = $msg + "$i"
	write-output $cur_msg
	Write-EventLog -LogName $ename -Source $src -EventID 3001 -EntryType Error -Message $cur_msg
	sleep(1)
	$i += 1
}
```

And I do see the "Log Group" named "ADFS_Debug" in my AWS Console.
And I do see the expected events.
![Screen Shot 2022-02-01 at 12 02 10 PM](https://user-images.githubusercontent.com/90734270/152024803-e7c34eab-7f9a-4378-93c5-1b48778d3165.png)
 
Can you try using this version of CloudWatch Agent and the PowerShell script?

**Comment by adam-mateen** [comment]
I ran the same test again with version `1.247346.0` and did not have an issue.
The Log Group appears in AWS Console and I can view the expected events.
I see these relevant debug messages in the Agent's log:
```
 D! [outputs.cloudwatchlogs] Pusher published 6 log events to group: ADFS_OLDEST stream: i-068404f568da63dc8 with size 0 KB in 367.5917ms.
```
The fact that I am using a PowerShell script to write events might be the reason it works for me.
Please run the PowerShell script and let me know if you see similar messages in your Agent log.
Thanks.
