### ISSUE TITLE
Cloudwatch agent stops sending logs after a few hours

### ISSUE THREAD

**Issue by zsolt-sb** [aws/amazon-cloudwatch-agent#180]
We have the cloudwatch agent up and running and we can see the logs coming through.  After several hours (and I've been told even a few days on some occasions, the cloudwatch agent stops sending logs to AWS.

I am not sure if this is relevent, but I do see within the cloudwatch logs:
```
021-03-04T22:51:54Z W! [outputs.cloudwatchlogs] Invalid SequenceToken used, will use new token and retry: The given sequenceToken is invalid. The next expected sequenceToken is: 49612984946004412055118931556677438474248778094089797074
2021-03-04T22:51:54Z W! [outputs.cloudwatchlogs] Retried 0 time, going to sleep 125.739149ms before retrying.
```

That said, the logs originally update just fine and the timing of the warning does not coincide with the failure to update.

If there is any way to run this with debugging please let me know and I will gladly provide that information.

Ubuntu 20.04.2 LTS 
Linux ip-10-65-53-134 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent --version
CWAgent/1.247347.5 (go1.15.6; linux; amd64) No Build Date

Source location:
  https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

**Comment by zsolt-sb** [comment]
I have demonstrated that the agent is actually still uploading the data so I will close this bug.
The problem is the local time stamp is slowly rolling backwards.  This makes current events appear as if they were occurring earlier than they were.  
The ingestion timestamp is correct and the eventid is moving forward correctly.  Just the local log timestamp is off.

I will look into this to see if I can find a root cause for the problem.  If it's an actual issue with the client I can open a new bug.

**Comment by Propfend** [comment]
I am having the same problem, the agent is configured to send the logs from a file, which is registering the logs of my system and systemd units. However, it stops sending logs after some minutes.
