### ISSUE TITLE
`make release` command fails at `go test`

### ISSUE THREAD

**Issue by mokemoketa** [aws/amazon-cloudwatch-agent#181]
### Summary
`make release` command fails at `go test`.

### Issue details
I cloned the code on new Amazon EC2 instances and followed the building steps at [README.md](https://github.com/aws/amazon-cloudwatch-agent#building-and-running-from-source), but `make release` fails at `go test`.

```
$ make release
...(snip)...
# github.com/aws/amazon-cloudwatch-agent/translator/util
translator/util/platform_windows.go:4:1: +build comment must appear before package clause and be followed by a blank line
...(snip)...
ok  	github.com/aws/amazon-cloudwatch-agent/translator/translate/metrics/util	0.004s
=== RUN   TestCreds
--- PASS: TestCreds (0.00s)
=== RUN   TestHostName
--- PASS: TestHostName (0.00s)
=== RUN   TestIpAddress
--- PASS: TestIpAddress (0.00s)
PASS
ok  	github.com/aws/amazon-cloudwatch-agent/translator/translate/util	0.003s
FAIL	github.com/aws/amazon-cloudwatch-agent/translator/util [build failed]
?   	github.com/aws/amazon-cloudwatch-agent/translator/util/ec2util	[no test files]
?   	github.com/aws/amazon-cloudwatch-agent/translator/util/ecsutil	[no test files]
?   	github.com/aws/amazon-cloudwatch-agent/translator/util/httpclient	[no test files]
FAIL
make: *** [Makefile:102: test] Error 2
```
I've already checked the similar issue https://github.com/aws/amazon-cloudwatch-agent/issues/123, but `sudo yum install -y gcc` didn't resolve this issue.
I've already verified building Agent by `make build` command succeeds itself.

Woud you check this issue and fix it?
If you need more information about my verification details or something is wrong with my verification, please let me know it.

Thanks,

### My verfication environments:
[code version]
- commit: b6df94b1df9ef6aa8e5105a42abc60bb14ca6392
(The current latest commit on *master* branch)

[OS]
I tried both of two OS below, but the result was the same.
- Amazon Linux 2
```
$ cat /etc/image-id
image_name="amzn2-ami-hvm"
image_version="2"
image_arch="x86_64"
image_file="amzn2-ami-hvm-2.0.20210219.0-x86_64.xfs.gpt"
image_stamp="2d25-8dac"
image_date="20210219214335"
recipe_name="amzn2 ami"
recipe_id="2388cb54-f1aa-0862-e76d-dca6-4b2b-8167-d379c05d"
```
- Red Hat Enterprise Linux 8.0
```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"
```
[Go version]
- 1.16
```
$ go version
go version go1.16 linux/amd64
```

**Comment by pingleig** [comment]
Thanks for the detailed issue! The problem is we didn't add proper build tag, there should be two errors. I think it got caught by newer version of go (i.e. 1.16), we are still using 1.15 when creating the release (internally).

```
# github.com/aws/amazon-cloudwatch-agent/translator/util
translator/util/platform_windows.go:4:1: +build comment must appear before package clause and be followed by a blank line
```

I created a PR #182 for it.
