### ISSUE TITLE
Support for Ubuntu x86

### ISSUE THREAD

**Issue by jrking4** [aws/amazon-cloudwatch-agent#185]
Currently run EC2 servers on Ubuntu x86, either version 20.04 or 18.04 
I have other services that require x86 and not ARM, one example is AWS Inspector agent, this only works on x86.

Do I need to build from source in order to utilize this tool?

**Comment by pingleig** [comment]
We have build for ubuntu (x86_64 i.e. amd64) and arm64, you can download if from s3. We don't have build for 32 bit (called 386 in GOARCH). You need to change [GOARCH](https://github.com/aws/amazon-cloudwatch-agent/blob/master/Makefile#L16) from `amd64` to `386`

```
# Makefile

# x86_64
LINUX_AMD64_BUILD = CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildmode=pie -ldflags="${LDFLAGS}" -o $(BUILD_SPACE)/bin/linux_amd64

# 32
LINUX_386_BUILD = CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -buildmode=pie -ldflags="${LDFLAGS}" -o $(BUILD_SPACE)/bin/linux_amd64

# change all the usage of LINUX_AMD64_BUILD or just do it in a more hacky way and replace amd64 with 386 in LINUX_AMD64_BUILD
```

Download link

- https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html

**Comment by jrking4** [comment]
Awesome!! Thank you so much!
