### ISSUE TITLE
[Feature Request] Support for multiple configuration files

### ISSUE THREAD

**Issue by gffqu** [aws/amazon-cloudwatch-agent#186]
In our organization we provide and enforce usage of preconfigured AMIs. As part of those AMIs we want to include CloudWatch agent with a default configuration. The goal is to have out of the box monitoring and logging for every EC2 instance, which is launched with any of the AMIs, while also giving app teams something to start with, not having to install and configure the defaults first.

We are struggling to combine this default configuration with the possibility for an app team to later on modify the configuration to add their own logs, metrics or aggregation dimensions.
We would like to separate default configuration from custom configuration, in order to be able to roll out new default configurations without breaking/overwriting the app teams custom configuration.
 
**Our key problem is: We can not preconfigure the AMI with one configuration file and let a projects load only an extension (covering e.g. only their application specific logs) with another configuration file. You cannot have 2 configuration files (the second only containing "extensions"). You have to integrate extensions by a project into the default configuration file.**

 
Our current solution for this is to split the configuration into multiple files, which we then merge back together (e.g. via shell scripts). I have attached a screenshot highlighting the different parts in that we split the configuration file.
 

We would like to have the possibility to simply include optional configuration files into the main config file (e.g. with a cwl-config.d directory as you might know it from other configurations). This would enable us to use the standard while achieving all of our requirements, instead of building our own solution, which requires the users to follow exactly our documentation (instead of relying on AWS documentation and standards).

![cloudwatch_agent_config](https://user-images.githubusercontent.com/80776187/111344737-f1755f80-867c-11eb-8812-b61ad37628e4.jpg)

**Comment by haojhcwa** [comment]
Just to clarify about your request, does the existing [Multiple CloudWatch Agent Configuration Files](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-common-scenarios.html#CloudWatch-Agent-multiple-config-files) in our common scenarios document address your issue?
We do understand there are some limitations of the current approach, most noticeably, we don't handle conflicting configurations for certain cases. However, it seems this existing feature fits your request pretty well.

**Comment by gffqu** [comment]
@haojhcwa Thank you very much for your reply. I have to admit I missed that part of the documentation and it looks like it could be helpful for at least parts of our problem. I will take a deeper look and get back to you, if that solves our issue or if anything is still open!

**Comment by jhnlsn** [comment]
This issue has gone stale, if you are still need our help please feel free to reopen.
