### ISSUE TITLE
[Feature Request] Allow metric type override for prometheus scrape

### ISSUE THREAD

**Issue by mjseid** [aws/amazon-cloudwatch-agent#187]
Currently metrics scraped from a prometheus exporter which are not typed are dropped by this agent. 

There are use cases (such as scraping  a prometheus server federate endpoint) where the the TYPE is not set.  It would be benefical to be able to override or set the TYPE for metrics to get around this limitation.  

Here is an example of this functionality in the datadog agent.
https://github.com/DataDog/integrations-core/pull/7071/files

**Comment by haojhcwa** [comment]
We have added this feature request to our todo list, will update here when we have any progress.
