### ISSUE TITLE
[Feature Request] - Add support for telegraf "inputs.nvidia_smi" to collect metrics on AWS GPU instances

### ISSUE THREAD

**Issue by amrragab8080** [aws/amazon-cloudwatch-agent#203]
Telegraf has native support for capturing metrics on NVIDIA backed GPU instances through the inputs.nvidia_smi plugin
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nvidia_smi

It would be great if we have this integrated into the CW agent.

**Comment by kreeser00** [comment]
Does this mean that amazon-cloudwatch-agent is not supported on GPU at all?  Or is this issue specific to GPU metrics?

**Comment by kreeser00** [comment]
Specifically, I'm wondering if logging can still be captured by the CW agent even though GPU metrics are not captured???  As of now, I am unable to get the CW agent running on GPU nodes of my EKS cluster.  It is configured as a DaemonSet for all nodes.  For CPU nodes the CW agent container is created and logging is captured but for GPU nodes the container never starts.

**Comment by kreeser00** [comment]
Logging is successfully captured by the CW agent.  Ability to capture metrics is still an outstanding issue.  The resolution to my specific issue was to add a toleration to the pod spec for our cloudwatch-agent DaemonSet.

**Comment by amrragab8080** [comment]
I created an implementation of pushing the GPU metrics into CW. You can see the packer snippet to integrate into you AMIs.

https://github.com/aws-samples/aws-efa-nccl-baseami-pipeline/blob/master/nvidia-efa-ami_base/nvidia-efa-ml-al2.yml#L155-L172

**Comment by jhnlsn** [comment]
This enhancement is slated for our next release milestone.  No completion date set yet though.

**Comment by vishalkg** [comment]
Any updates ?

**Comment by SaxyPandaBear** [comment]
This was released in late February. See https://aws.amazon.com/about-aws/whats-new/2022/02/amazon-cloudwatch-agent-nvidia-metrics/
