### ISSUE TITLE
Configuration file cannot end in '.tmp'

### ISSUE THREAD

**Issue by rifftual** [aws/amazon-cloudwatch-agent#204]
If the configuration file ends up with '.tmp' suffix, CloudWatch agent will try to locate it with '.tmp.tmp' suffix. This is problematic in Windows, because you might automate the creation of the config file (Since it can be temporary from the automatic deployment POV) and use [New-TemporaryFile](New-TemporaryFile) which will add the `.tmp` suffix.

**Comment by rifftual** [comment]
So, our automation creates a config file using `New-TemporaryFile` and feeds that file to `amazon-cloudwatch-agent-ctl.ps1`. Then `amazon-cloudwatch-agent-ctl.ps1` copies the config file to CloudWatch's agents internal data directory and does not append the `.tmp` prefix. But for some reason the agent tries to locate the file with `.tmp.tmp` suffix. I'm guessing there's a mismatch between copying and reading the file, the agent uses the original name + `.tmp` suffix but `amazon-cloudwatch-agent-ctl.ps1` does not add an additional `.tmp` suffix if it already exists. Just guessing here what might be the problem.

**Comment by jhnlsn** [comment]
Is there an alternative method that you can use to create the config file instead of creating a tmp file?
