### ISSUE TITLE
[Feature Request] Possibility to specify retention period in Cloud Watch log group names

### ISSUE THREAD

**Issue by volphy** [aws/amazon-cloudwatch-agent#217]
It would be nice to have a new configuration option added to the logs section:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html

It could be called:
log_group_retention
It should allow specifying a non-default retention period setting.

I have observed that using Amazon Cloud Watch Agent (amazon-cloudwatch-agent-1.247347.4-1.amzn2.x86_64 RPM) creates a new Cloud Watch log group without any retention period set ('Never expire').

**Comment by jefchien** [comment]
I'll take a look at this.

**Comment by dacodas** [comment]
Would love this, and am pumped to see the MR go through
