### ISSUE TITLE
Windows: Cannot update common-config.toml

### ISSUE THREAD

**Issue by rifftual** [aws/amazon-cloudwatch-agent#220]
The configuration file `common-config.toml` cannot be updated once the service is installed: `The process cannot access the file 'C:\ProgramData\Amazon\AmazonCloudWatchAgent\common-config.toml' because it is being used by another process`

Stopping the agent with `& 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a stop -m OnPremise` doesn't help. The agent seems to stop (According to `status`) but the service is stuck in `Start pending` and apparently still spawns processes that prevent writing that file.

**Comment by shaochengwang** [comment]
> Stopping the agent with & 'C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1' -a stop -m OnPremise doesn't help. The agent seems to stop (According to status) but the service is stuck in Start pending and apparently still spawns processes that prevent writing that file.

Do you mean a new instance will be started again immediately after you stop agent through the command? And that makes you not able to update common-config?

**Comment by rifftual** [comment]
@shaochengwang yes, the service seems to stay alive when I stop using `amazon-cloudwatch-agent-ctl.ps1`. Stopping the service using `Stop-Service` doesn't help and neither does directly killing the processing since they will be respawned.
