### ISSUE TITLE
Send Prometheus metrics from local endpoint to Cloudwatch

### ISSUE THREAD

**Issue by bruceharrison1984** [aws/amazon-cloudwatch-agent#221]
I'm trying to use cloudwatch-agent to forward Prometheus metrics to Cloudwatch Metrics. I have a Prometheus endpoint available on `127.0.0.1` and the CWAgent successfully retrieves metrics from it, but fails to upload them to Cloudwatch.

I'm not sure if this is a valid use-case, since most CWAgent/Prometheus docs seem to relate only to ECS/EKS. However, following the documentation [here](https://docs.amazonaws.cn/en_us/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-PrometheusEC2.html) has got my 99% of the way towards what I am trying to do.

My `metrics_collected` configuration is as follows (within "logs"):
```json
...
"metrics_collected": {
  "prometheus": {
    "log_group_name": "/{hostname}",
    "prometheus_config_path": "/custom/config/prometheus.yml",
    "emf_processor": {
      "metric_declaration_dedup": true,
      "metric_namespace": "custom-prometheus",
      "metric_unit": {
        "custom_metric_Mem_resident_int": "Count",
        "custom_metric_RTS_gcHeapBytes_int": "Count",
      },
      "metric_declaration": [
        {
          "source_labels": [
            "job"
          ],
          "label_matcher": "custom-metrics",
          "dimensions": ["instance"],
          "metric_selectors": [
            "^custom_metric.*"
          ]
        }
      ]
    }
  }
}
...
```

My prometheus `scrape_config` is as follows:
```yml
global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
- job_name: custom_metrics
  sample_limit: 10000
  static_configs:
    - targets: 
      - 127.0.0.1:12798
      labels:
        application: custom-node
        os: amazon-linux-2

```

My metrics endpoint produces the following:
```sh
...
custom_metric_Mem_resident_int 350982144
custom_metric_RTS_gcHeapBytes_int 327155712
...
```

Cloudwatch successfully starts, as well as pulls the metrics from the local endpoint, however every single metrics fails with the same error:

```sh
2021-06-04T14:57:31Z E! metricsHandler NO metaData for custom_metric_Mem_resident_int | 127.0.0.1:12798 | custom_metrics
2021-06-04T14:57:31Z E! metric_type ERROR: custom_metric_Mem_resident_int |custom_metrics|127.0.0.1:12798|
2021-06-04T14:57:31Z E! metricsHandler NO metaData for custom_metric_RTS_gcHeapBytes_int | 127.0.0.1:12798 | custom_metrics
2021-06-04T14:57:31Z E! metric_type ERROR: custom_metric_RTS_gcHeapBytes_int |custom_metrics|127.0.0.1:12798|
```

CWAgent is clearly getting values from the /metrics endpoint, but then drops them all. I'm not sure what exactly this error is trying to tell me, since the unit type is set on both of the metrics. I have truncated the number of metrics for readability here, but there are 30+ metrics that are not defined in my CWAgent config that appear in this output as well, which verifies my suspicions that the CWAgent is recieving metrics from Prometheus.

I haven't had any luck trying different dimensions, units, labels, or selectors. No matter what the configuration I use, I receive the same error and all Prometheus metrics are discarded without sending them to Cloudwatch.

Normal log forwarding works fine, so I don't think it is an IAM permissions issue.

Is this just an invalid use case for the Prometheus scraping ability of CWAgent?

**Comment by pingleig** [comment]
What library you are using to generate the promtheus metrics? The error log means cw agent try to get type of the metrics but failed to do so.

https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-example

```
// We are expecting type information
TYPE custom_metric_Mem_resident_int summary
custom_metric_Mem_resident_int 350982144
```

@pxaws would have more context on this.

**Comment by bruceharrison1984** [comment]
The Prometheus metrics are generated by an application that is running on the server. Sadly, I don't believe I have the ability to alter the output of the /metrics endpoint, though it is strange that it is outputting generally invalid metrics.

**Comment by liuyangc3** [comment]
same here

the metric
```
# HELP web_req_created Total of HTTP requests processed
# TYPE web_req_created gauge
web_req_created{handler="UserapiAllMiningUsersHandler",status="2xx"} 1.6267785847137797e+09
```

the error
```
2021-07-22T02:36:27Z E! metric_type ERROR: web_req_created|myjob|localhost:8100|
2021-07-22T02:36:27Z E! metricsHandler NO metaData for web_req_created | localhost:8100 | myjob
```

**Comment by liuyangc3** [comment]
I am surprised by after changing the metrics in my config
```
"metric_declaration": [
        {
          "source_labels": ["job"],
          "label_matcher": "docker",
          "dimensions": ["instance"],
          "metric_selectors": [
            // "^ web_req_created$",  <-------- I removed this metric
             "^ web_req_total$"
          ]
```

I can still get ERROR of `web_req_created`
```
2021-07-22T06:16:02Z E! metricsHandler NO metaData for web_req_created | localhost:8200 | f2pool-web
2021-07-22T06:16:02Z E! metric_type ERROR: web_req_created|f2pool-web|localhost:8200|
```

**Comment by pxaws** [comment]
`metric_declaration` is used to filter out metrics and the filtering happens after prometheus scrapes the metrics. The metrics scraping is controlled by the prometheus config
```
scrape_configs:
  - job_name: f2pool-web
    static_configs:
      targets:
        - localhost:8200
```

To get rid of `f2pool-web` completely, you should delete the job from the prometheus config. To check how to configure prometheus scrapping, see this: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

**Comment by renesecur** [comment]
Hi Bruce, did you find a workaround for this? Assuming the server does not export type information?

**Comment by bruceharrison1984** [comment]
@renesecur nope, the server doesn't include type information, so I cannot use this feature of the CWA. I ended up using a third party library that can scrape Prometheus metrics and turn them into Cloud watch metrics.

**Comment by richturner** [comment]
I am seeing this ` E! metric_type ERROR` for timestamp metrics relating to summary output; these metrics have valid metadata in the metrics output but cloudwatch doesn't like it; seems to be the same issue as a user above mentioned;

> What library you are using to generate the promtheus metrics? The error log means cw agent try to get type of the metrics but failed to do so.
> 
> https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-example
> 
> ```
> // We are expecting type information
> TYPE custom_metric_Mem_resident_int summary
> custom_metric_Mem_resident_int 350982144
> ```
> 
> @pxaws would have more context on this.

Also several counter metrics show 0 values in the Cloudwatch logs but the metrics endpoint being scraped has values >0 so the data is unreliable.

Was wrongly assuming that this Prometheus ingestion was well polished but that doesn't seem to be the case.

@bruceharrison1984 What third party tool are you using to do your Prometheus CW ingestion?

**Comment by richturner** [comment]
Possibly related to this issue:

https://github.com/prometheus/prometheus/issues/6541

The exporter I am using is outputting `_created` metrics which is in the OpenMetrics standard but prometheus doesn't seem to handle them well and seems CWAgent doesn't either.

Will see if I can tweak the exporter to not output the OpenMetrics `_created` metrics.

**Comment by richturner** [comment]
Managed to configure exporter to not output `_created` series and the errors are now gone from the cloudwatch agent logs.

Unfortunately the metric values appearing in cloudwatch are still incorrect; is there some quirk to how `metric_declarations` should be used? Should I just put one metric per `metric_declaration`, I've tried grouping them so far based on common dimensions
