### ISSUE TITLE
Config (Append) Documentation Request

### ISSUE THREAD

**Issue by taylorbartley** [aws/amazon-cloudwatch-agent#238]
My team and I are working on standardizing log/metrics configurations. I've noticed some behaviors when using the Configure and Configure (append) options, and I'd like for them to be documented explicitly please. 
Extra context: We've only made it through AmzLinux2 Instances, but I'm sure the behaviors are similar across the various OSs, just with differing file paths. 

Through practice, there's a `/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml` created after configure or append. This would indicate that _this_ file is what is used for active configuration while the agent is operating. 
However, I've noticed that there are json-type files created in `/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/` that reflect the contents of SSM parameters. It seems that these files are more important for active operation, as deleting any of them will immediately break logging/reporting.

Another pain point has been appending configurations for metrics. I've seen that adding an entire `metrics` body is fine. 
Example:
```json
"metrics_collected": {
    "disk": {
        "measurement": ["disk_used_percent"],
        "resources": ["*"],
        "ignore_file_system_types": ["tmpfs", "devtmpfs"],
        "drop_device": true
    }
}
```

Append
```json 
{
    "metrics": {
        "metrics_collected": {
            "mem": {
            "measurement": ["mem_used_percent"]
            }
      }
    }
}
```
This will result in a successful merge.

However, changing _any_ value of a field, or even adding a field, within an existing metric will result in a conflict. 
```json
"metrics_collected": {
    "disk": {
    "measurement": ["disk_used_percent"],
    "resources": ["*"]
    }
}
```
Append
```json 
"metrics_collected": {
    "disk": {
    "measurement": ["disk_inodes_free"],
    "resources": ["*"],
    }
}
```
results in a conflict. Why is this? 
So far I've seen these common conflicts:
- Extending/adding to a measurement
- Adding a property, e.g., "ignore_file_system_types"
- Adding "append_dimensions"
- Adding an extra dimension within the "append_dimensions"
I haven't been able to force any conflicts for logging additions. Conflicts only seem to occur with metrics. 

Standardizing our CloudWatch Agent configurations would be simpler if there was some indication of expected behavior from using the commands provided. 
I can provide more test cases if needed. 
Thank you.

**Comment by haojhcwa** [comment]
CWAgent binary would use the `amazon-cloudwatch-agent.toml` file as the final config, it is considered an internal state that we do not recommend customers to modify directly.

We really appreciate listing the pain points, we will discuss if we can lose up the conflict rules without making the operation ambiguous.
