### ISSUE TITLE
Configurable Log group name.

### ISSUE THREAD

**Issue by danielleswyhart** [aws/amazon-cloudwatch-agent#248]
https://github.com/aws/amazon-cloudwatch-agent/blob/c785fd73b33c5b2793c3f5934f2aa66a9a016eb9/plugins/processors/k8sdecorator/structuredlogsadapter/utils.go#L51

We would like to customize the log group path but it is hard coded here. Could we please get this changed to support the ability to output this to a custom loggroup?

**Comment by mxiamxia** [comment]
CWAgent supports ContainerInsights in EKS/ k8s / ECS. The logs group has to be in such pattern so the ContainerInsihgts metrics can be auto-dashboarded. There is no way to customized it for k8s/EKS metrics for it yet.

**Comment by jhnlsn** [comment]
no-fix
