### ISSUE TITLE
[Feature Request] option to create alarms from config file

### ISSUE THREAD

**Issue by ramadis** [aws/amazon-cloudwatch-agent#251]
### Why

It seems to be a common use case to create new alarms from the metrics captured using the CloudWatch agent. Current solutions include defining them in a CloudFormation template, creating custom AWS Lambda functions to create them, and other workarounds. These solutions are far from perfect, as they come with [other issues](https://github.com/aws/amazon-cloudwatch-agent/issues/161).

### Proposal

Make the CloudWatch agent create the alarms, as defined in the configuration file. I propose supporting a new `alarm` field in the measurement object, supporting the required fields to [create a new metric alarm](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html). For instance:

```json
{
  "agent": {...},
  "logs": {...},
  "metrics": {
    "namespace": ...,
    "append_dimensions": {...},
    "metrics_collected": {
      "mem": {
        "measurement": [
          {
            "name": "used_percent",
            "rename": "MemoryUtilization",
            "unit": "Percent",
            "alarm": {
              "actions": ["arn:aws:sns:us-west-1:..."],
              "comparisonOperator": "GreaterThanThreshold",
              "datapointsToAlarm": 3,
              "evaluationPeriods": 4,
              "period": 60,
              "statistic": "Average",
              "threshold": 40,
              "description": "CPU Utilization of ${aws:InstanceId} with 40% as threshold",
              "name": "Instance ${aws:InstanceId} CPU Utilization"
            }
          }
        ]
      }
    }
  }
}
```

This proposal could be eventually extended to support composite alarms.

**Comment by jhnlsn** [comment]
Hey Rama,

Thanks for submitting the feature request!  While this seems like an interesting concept, I think it ends up outside of the scope of the Cloudwatch agent that we would like to support.
