### ISSUE TITLE
Prometheus counter metrics generated prior to the initial scrape are lost

### ISSUE THREAD

**Issue by 56KBs** [aws/amazon-cloudwatch-agent#258]
### Summary

When gathering Prometheus metrics, any counter metrics occurring prior to the first scrape are lost and ignored.

#### Reproducing

- Deploy service exposing a Prometheus counter metric
- Increase the counter to 1
- Deploy CloudWatch agent to scrape this service
- Observe the CloudWatch agent reporting no values for the metrics
- Increase the counter to 2
- Observe the CloudWatch agent reporting the metrics value as 1

### Cause

From reviewing the code for the Prometheus scraping I can see that this is being caused by the delta calculation behaviour within the `prometheus_scraper`.

The delta calculator will not return any data in the scenario it is the first time the metric has been seen - It will however store it within it's cache. On subsequent occurrences of the metric, a delta will be calculated and returned.

### My Use Case

I am using the CloudWatch agent to scrape Prometheus metrics from Fargate tasks and losing this metric data throws off our dashboarding/reports.

This issue is particularly painful on our Fargate tasks that auto-scale when under load as those services immediately start processing and generating metrics prior to the CloudWatch agent scraping, resulting in large chunks of data going missing - For example within a load test scenario we're seeing over half the data in the metrics go missing over the course of a short test.

### Configuration
<details>
    <summary>CloudWatch Agent Configuration</summary>

I've shortened `metric_declaration` to a single entry for brevity

```json
{
  "agent": {
    "debug": true
  },
  "logs": {
    "metrics_collected": {
      "prometheus": {
        "prometheus_config_path": "env:PROMETHEUS_CONFIG_CONTENT",
        "ecs_service_discovery": {
          "sd_result_file": "/tmp/cwagent_ecs_auto_sd.yaml",
          "docker_label": {}
        },
        "emf_processor": {
          "metric_declaration": [
            {
              "source_labels": ["container_name"],
              "label_matcher": "^smtp-egress$",
              "dimensions": [
                ["ClusterName", "TaskDefinitionFamily"],
                ["ClusterName", "TaskDefinitionFamily", "acked"]
              ],
              "metric_selectors": [
                "^smtp_egress_queue_subscriber_messages_received_total$"
              ]
            },
          ]
        }
      }
    },
    "force_flush_interval": 60
  }
}
```
</details>

<details>
    <summary>Prometheus Configuration</summary>

```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: cwagent-ecs-file-sd-config
    sample_limit: 10000
    file_sd_configs:
      - files: [ "/tmp/cwagent_ecs_auto_sd.yaml" ]
```
</details>

**Comment by jhnlsn** [comment]
What is your cloudwatch agent configuration

**Comment by 56KBs** [comment]
> What is your cloudwatch agent configuration

I've added our CloudWatch agent configuration & Prometheus configuration into the original issue description

**Comment by AlexHasMe** [comment]
@56KBs Did you find a solution for the problem? I am facing the same problem with cloudwatch agent for prometheus.

**Comment by 56KBs** [comment]
> @56KBs Did you find a solution for the problem? I am facing the same problem with cloudwatch agent for prometheus.

We run a fork of the cloudwatch agent in order to work around the issue
