### ISSUE TITLE
Debian 11 arm64 

### ISSUE THREAD

**Issue by magenx** [aws/amazon-cloudwatch-agent#262]
```
wget https://s3.amazonaws.com/amazoncloudwatch-agent/debian/arm64/latest/amazon-cloudwatch-agent.deb
--2021-08-21 18:41:22--  https://s3.amazonaws.com/amazoncloudwatch-agent/debian/arm64/latest/amazon-cloudwatch-agent.deb
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.97.165
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.97.165|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-08-21 18:41:22 ERROR 403: Forbidden.
```

it looks like cloudwatch agent not available for Debian 11 arm64 link return 403

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-commandline-fleet.html
there are lots of installation links, but only **Debian ARM64** is missing.

**Comment by jhnlsn** [comment]
We do not currently provide pre-built binaries for debian arm64

**Comment by andytson-inviqa** [comment]
please can you provide them then

**Comment by antoine-sachet** [comment]
Could you please provide the binary for the cloudwatch agent on debian ARM64? 

It literally is the only one missing from the list - all other distributions have both x86 and arm64.

Thanks!
