### ISSUE TITLE
Question/Feature request:  Allow for specifying prometheus scheme and tls_config in ecs service discovery.

### ISSUE THREAD

**Issue by ericbrumfield** [aws/amazon-cloudwatch-agent#316]
I ran into in a gov environment where containers are specifically only exposing https using certs that may or may not be trusted from where cloudwatch agent is running at in a prometheus scraping config and setup in ECS.  I haven't seen a way yet to be able to specify the scheme for https in the ecs service discovery setups with the cloudwatch agent.  Similarly it'd be useful to have the tls_config parts be able to be configured in the ecs service discovery configuration.  Not everyone is running ECS containers that have http exposed and the cloudwatch agent and prometheus setup seems to be fixed on only http currently.  The environment I was working in was strictly Fargate.

Is there a way to configure the agent like this so that one would not have to expose http or setup additional sidecar proxies in order to scrape prometheus metrics in ECS over https?

**Comment by jhnlsn** [comment]
There is a `common-config.toml` file located in `/opt/aws/amazon-cloudwatch-agent/etc` where you will find an `ssl` section.  You can set the `ca_bundle_path` to the location of your private bundle.  This should take care of the issue.
