### ISSUE TITLE
Log collection: multi_line_start_pattern not working

### ISSUE THREAD

**Issue by atostek-koskela-vesa** [aws/amazon-cloudwatch-agent#321]
We currently have a number of logs where a single log entry can be multiple lines, which is why we need to use the multi_line_start_pattern. An anonymized example of our amazon-cloudwatch-agent configuration:
```
{
    "logs": {
        "logs_collected": {
            "collect_list": [
                {
                    "file_path": "/path/to/log/service.*.log",
                    "log_group_name": "application/service",
                    "timezone": "UTC",
                    "timestamp_format": "%Y-%m-%d %H:%M:%S.%f",
                    "multi_line_start_pattern": "{timestamp_format} |"
                }
            ]
        }
    }
}
```
We have a daily rotating log files that are in the format of service.yyyy.mm.dd.log. Hence the "service.*.log" on file_path.

An anonymized example of a log entry:
```
yyyy-mm-dd HH:mm:ss.SSS | loglevel | thread | logger | log message
second line of log message
third line of log message
fourth line of log message
fifth line of log message
sixth line of log message
seventh line of log message
eighth line of log message
ninth line of log message
tenth line of log message
yyyy-mm-dd HH:mm:ss.SSS | loglevel | thread | logger | second log message
```

With this setup, when I'm looking the logs from Cloudwatch, the logs look the following:
![cloudwatch-log-entries-censored](https://user-images.githubusercontent.com/94905389/143243752-e507220d-f15d-4019-977c-ab477f2c5610.png)
 
Changing the logs to JSON format isn't currently feasible, so getting the multi_line_start_pattern to work is necessary. Is the configuration wrong, or is the problem in a filter somewhere?

**Comment by atostek-koskela-vesa** [comment]
[troubleshoot_example.log](https://github.com/aws/amazon-cloudwatch-agent/files/7596097/troubleshoot_example.log)
Here is an anonymized example log of what we have. And here's what it looks like in Cloudwatch.
![cloudwatch_example_log](https://user-images.githubusercontent.com/94905389/143249180-85795556-0da4-41ed-bc7f-e5aa3bc1cb25.png)

**Comment by SaxyPandaBear** [comment]
I think that the configuration you have is malformed. Looking at the [code](https://github.com/aws/amazon-cloudwatch-agent/blob/c785fd73b33c5b2793c3f5934f2aa66a9a016eb9/translator/translate/logs/logs_collected/files/collect_list/ruleMultiLineStartPattern.go#L13) that reads in the configuration, it checks if the `multi_line_start_pattern` key maps to `"{timestamp_format}"`, but in what you have provided, there are extra characters at the end: `"{timestamp_format} |"` Can you try taking out the extra whitespace and `|` character to see what happens?

**Comment by atostek-koskela-vesa** [comment]
The point of the extra whitespace and `|` is to separate the log entry starting timestamp from other possible timestamps that might occur in the log. As you can see in the example log, the first line of a log entry is `yyyy-mm-dd HH:mm:ss.SSS | <rest of the entry>`, so the whitespace and `|` provide additional context to where the log entry starts.

I tested without the whitespace and `|`, and it seems to now work as intended. So apparently it was malformed as you suspected. So this might require some changes in the configuration instructions of these, since I did read through them trying to figure out how I should write out this extra context. Based on the code, it seems to only accept the `"{timestamp_format}"` value, while the instructions give an impression that one could define whatever pattern their log entry has.

**Comment by SaxyPandaBear** [comment]
Closing this out since there wasn't an issue with the `multi_line_start_pattern` configuration.
