### ISSUE TITLE
[Question] How to setup emf in Beanstalk (docker) env

### ISSUE THREAD

**Issue by miguelcss** [aws/amazon-cloudwatch-agent#322]
Hello CloudWatch community, 

I'm trying to use CloudWatch Embedded format [link](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_CloudWatch_Agent.html) inside a beanstalk environment running docker image/pre-set. 

I'm able to configure an agent locally to emmit the emf metrics like so:

```
{
  "logs": {
    "metrics_collected": {
      "emf": { }
    }
  }
}
```

However I'm not able to find the namespace definition to pass emf configuration to beanstalk , using the ```.ebextensions```. 
The available namespaces seem to just stream the existing logs [link](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-cloudwatchlogs).

In the ec2 instance, under ```/opt/aws/amazon-cloudwatch-agent/doc```  I see that the amazon-cloudwatch-agent-schema.json does not have any ```emf``` entry for beanstalk. 

How can I enable emf in a CloudWatch environment  running in beanstalk?

**Comment by miguelcss** [comment]
Any feedback ? Help is appreciated

**Comment by miguelcss** [comment]
Ping, any feedback? thank you

**Comment by jhnlsn** [comment]
From what I can tell, they are not using cloudwatch agent to ship the logs to cloudwatch logs.  If you have additional questions about beanstalk or configuration they provide. you would have to open a support ticket with that service directly.
