### ISSUE TITLE
ECS Service Discovery: Default Network Mode

### ISSUE THREAD

**Issue by griffinmyers** [aws/amazon-cloudwatch-agent#330]
When evaluating tasks for ECS Service Discovery, this repo uses the network mode defined on a task's task definition to resolve which [IP](https://github.com/aws/amazon-cloudwatch-agent/blob/1df147021064e850a90101b124a4377940112b4e/internal/ecsservicediscovery/decoratedtask.go#L70-L92) or [port](https://github.com/aws/amazon-cloudwatch-agent/blob/1df147021064e850a90101b124a4377940112b4e/internal/ecsservicediscovery/decoratedtask.go#L94-L123) should be used as the scrape target. 

Unfortunately, these bits of logic aren't sensitive to the default network mode that kicks in when not specified in a task definition: 

> **`networkMode`**
> 
> Type: string
> 
> Required: no
> 
> The Docker networking mode to use for the containers in the task. For Amazon ECS tasks hosted on Amazon EC2 Linux instances, the valid values are none, bridge, awsvpc, and host. **If no network mode is specified, the default network mode is bridge**. For Amazon ECS tasks hosted on Amazon EC2 Windows instances, the valid values are default, and awsvpc. **If no network mode is specified, the default network mode is used.**
> 
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

Are folks open to updating this behavior to handle the default cases, and if so are their opinions about exactly how this logic should be handled? I'm happy to draft up a PR, but wanted to get some sense of directional alignment here first. 

Thanks!

**Comment by javabrett** [comment]
Thanks @griffinmyers .

Otherwise stated, `TaskDefinition.NetworkMode == nil` is valid and should select the platform-default network mode, but at:

https://github.com/aws/amazon-cloudwatch-agent/blob/c3894b985db74b51a8dc07f087e1a2da698dff2b/internal/ecsservicediscovery/decoratedtask.go#L68-L73

... fails to resolve the private IP address and the task if silently dropped and filtered-out.  On Linux, the logic should be per `bridge` and operate as if that mode was explicitly-defined.

**Comment by griffinmyers** [comment]
@javabrett exactly. I think we'll additionally want to apply this logic when determining which port to scrape:

https://github.com/aws/amazon-cloudwatch-agent/blob/c3894b985db74b51a8dc07f087e1a2da698dff2b/internal/ecsservicediscovery/decoratedtask.go#L97-L100

**Comment by adam-mateen** [comment]
Thanks for finding this bug and opening this issue.
CloudWatch Agent is using `aws-sdk-go` and calling `ecs.DescribeTaskDefinition()`:
https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.DescribeTaskDefinition
It would have been nice if the AWS API returned the actual networkMode used by the task, but I am sure someone else would complain that it should return exact text of the task definition.

So now the CWA must also contain logic for translating networkMode = "".
Let's all hope the default AWS SDK behavior never changes.
