### ISSUE TITLE
Coding bug to check whether value set of _maxBufferTimeStamp

### ISSUE THREAD

**Issue by monty241** [aws/amazon-cloudwatch-agent#378]
AWSLoggerCore.cs:
```
        private DateTime _maxBufferTimeStamp = new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Utc);
```
But on line 257:
```
if (_maxBufferTimeStamp == DateTime.MinValue)
```
Both values happen to maybe refer to the same constant.

Note that the kind is Utc on init, but MinValue is Unspecified. Probably some refactoring operation forgotten.

Suggested change is to use `DateTime?` or introduce a readonly static DateTime to indicate "unset".

**Comment by SaxyPandaBear** [comment]
I think you're referring to https://github.com/aws/aws-logging-dotnet/blob/083aa47f454de5b5b60e8ca3c5829d2d1f415060/src/AWS.Logger.Core/Core/AWSLoggerCore.cs, which isn't part of this project.

**Comment by monty241** [comment]
My apologies; I was already wondering where fork had gone.
