### ISSUE TITLE
auto_removal will drop log lines from old file when new file discovered

### ISSUE THREAD

**Issue by adam-mateen** [aws/amazon-cloudwatch-agent#381]
If a user has a log config with:
```
 "file_path": "/tmp/foo.log*",
 "auto_removal": true
```
And they write to a file `/tmp/foo.log.2020-01-02` very rapidly, it is possible CWAgent could fall behind tailing that file.
And when the user starts writing to `/tmp/foo.log.2020-01-03` it is possible CWAgent has not finished sending all those lines from the old file.

In this case it will intentionally drop lines.
But the user doesn't want to drop lines 😢 

In `FindLogSrc()`:
```
if _, ok := dests[filename]; ok {
	continue
} else if fileconfig.AutoRemoval { // This logic means auto_removal does not work with publish_multi_logs
	for _, dst := range dests {
		dst.tailer.StopAtEOF() // Stop all other tailers in favor of the newly found file
	}
}
```

`StopAtEOF()` has a comment making it seem like the intention was read until the end...
```
// StopAtEOF stops tailing as soon as the end of the file is reached.
func (tail *Tail) StopAtEOF() error {
	tail.Kill(errStopAtEOF)
	return tail.Wait()
}
```
However `Tail.sendLine()` stops and drops lines if `Tail.Dying()` is set for any reason, including `errStopAtEOF`:
```
// sendLine sends the line(s) to Lines channel, splitting longer lines
// if necessary. Return false if rate limit is reached.
func (tail *Tail) sendLine(line string, offset int64) bool {
	now := time.Now()
	lines := []string{line}

	// Split longer lines
	if tail.MaxLineSize > 0 && len(line) > tail.MaxLineSize {
		lines = partitionString(line, tail.MaxLineSize)
	}

	for i, line := range lines {
		// This select is to avoid blockage on the tail.Lines chan
		select {
		case tail.Lines <- &Line{line, now, nil, offset}:
		case <-tail.Dying():
			tail.dropCnt += len(lines) - i
			return true
		}
	}
```

Please consider changing CWAgent to wait for tailer to actually read and report all lines from the old file before auto removing it.

**Comment by adam-mateen** [comment]
1 reason to not change would be if there are users that write to a file continuously, even after the "new" file has been created and is being written. This doesn't make sense to me, at least not when I think of log rotation. If anyone else things of a reason why it would be desired please let me know.

**Comment by jhnlsn** [comment]
Looked through this a little bit more and there appears to be an issue with the way that Dying is handled in the sendLine function.

in your first point: StopAtEOF is called and sends errStopAtEOF error.

In the tailFileSync function, the for loop is allowed to continue based on 
```
case <-tail.Dying():
			if tail.Err() == errStopAtEOF {
				continue
			}
```

which means that sendLine should probably be changed to match that same case.

```
case <-tail.Dying():
			tail.dropCnt += len(lines) - i
			return true
		}
``` 

should be changed to check if the `tail.Err()` is `errStopAtEOF` and if it is, do not increment the dropped lines.  Lines will not be dropped when the error is `errStopAtEOF`.

I hope i'm reading that right

**Comment by adam-mateen** [comment]
public documentation:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html
>auto_removal – Optional. If this is true, the CloudWatch agent automatically removes old log files after they are uploaded to CloudWatch Logs. The agent only removes complete files from logs that create multiple files, such as logs that create separate files for each date. If a log continuously writes to a single file, it is not removed.
If you already have a log file rotation or removal method in place, we recommend that you omit this field or set it to false.
If you omit this field, the default value of false is used.

Based on this, CWA should only delete "old log" after it has been uploaded. In other words, NOT drop log lines.
