### ISSUE TITLE
Missing --help output

### ISSUE THREAD

**Issue by ecerulm** [aws/amazon-cloudwatch-agent#393]
I installed the official release for macOS at the moment

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent --version
CWAgent/1.247350.0 (go1.15.15; darwin; amd64) No Build Date

When I use `--help` or `-h` I guess no output: 

```
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent --help
```

From the source code of [amazon-cloudwatch-agent.go](https://github.com/aws/amazon-cloudwatch-agent/blob/670643d2b4dc633a94f0938477f5addeb1c5c8fe/cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go#L52-L90) it seems that the description of each flag is already there in the source code but **it's not used**.

For those of us that are trying amazon-cloudwatch-agent locally for troubleshooting purpose it would be very convenient to have a working `--help`. I'm not sure if this is a regression or `--help` was never implemented but it would be really helpful to get it to work.

**Comment by ecerulm** [comment]
I just commented out [line 391 of amazon-cloudwatch-agent.go](https://github.com/aws/amazon-cloudwatch-agent/blob/670643d2b4dc633a94f0938477f5addeb1c5c8fe/cmd/amazon-cloudwatch-agent/amazon-cloudwatch-agent.go#L391) 

and then `./build/bin/darwin_amd64/amazon-cloudwatch-agent --help` produces a more helpful output: 

```
./build/bin/darwin_amd64/amazon-cloudwatch-agent --help
Usage of ./build/bin/darwin_amd64/amazon-cloudwatch-agent:
  -aggregator-filter string
    	filter the aggregators to enable, separator is :
  -config string
    	configuration file to load
  -config-directory string
    	directory containing additional *.conf files
  -console
    	run as console application (windows only)
  -debug
    	turn on debug logging
  -envconfig string
    	env configuration file to load
  -input-filter string
    	filter the inputs to enable, separator is :
  -input-list
    	print available input plugins.
  -output-filter string
    	filter the outputs to enable, separator is :
  -output-list
    	print available output plugins.
  -pidfile string
    	file to write our pid to
  -pprof-addr string
    	pprof address to listen on, not activate pprof if empty
  -processor-filter string
    	filter the processors to enable, separator is :
  -quiet
    	run in quiet mode
  -sample-config
    	print out full sample configuration
  -schematest
    	validate the toml file schema
  -section-filter string
    	filter the sections to print, separator is ':'. Valid values are 'agent', 'global_tags', 'outputs', 'processors', 'aggregators' and 'inputs'
  -service string
    	operate on the service (windows only)
  -service-display-name string
    	service display name (windows only) (default "Telegraf Data Collector Service")
  -service-name string
    	service name (windows only) (default "telegraf")
  -setenv string
    	set an env in the configuration file in the format of KEY=VALUE
  -test
    	enable test mode: gather metrics, print them out, and exit
  -test-wait int
    	wait up to this many seconds for service inputs to complete in test mode
  -usage string
    	print usage for a plugin, ie, 'telegraf --usage mysql'
  -version
    	display the version and exit
```

Was the `--help` output suppressed on purpose?  If so, why? It would be good to document in the source code

**Comment by SaxyPandaBear** [comment]
To your question, I think that it was taken from [telegraf](https://github.com/influxdata/telegraf/blob/master/internal/usage.go#L6). Which is probably why it was commented out.
