### ISSUE TITLE
Increasing the Number of Supported Dimensions in a Metric

### ISSUE THREAD

**Issue by sethAmazon** [aws/amazon-cloudwatch-agent#398]
Cx has been asking to increase max dim to at min 20.
Backend will soon support max dim of 30 and size of 1024.
Do not merge until backend changes are done.

**Comment by khanhntd** [comment]
There are some curious questions from me:
* Can you clarify why we would need a cert confirm in the logs (`x509: certificate signed by unknown authority`)?
* Would you add the `35 metrics dimension` test case for it?
