### ISSUE TITLE
Feature request: print out how many files the agent is currently monitoring on demand

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/amazon-cloudwatch-agent#432]
It'd be nice if there was a way to print out or log how many files the agent is currently tailing at any given point in time. The agent allows for glob-like syntax to discover files to tail, so people can pretty easily provide a bad log configuration that explodes CPU usage.

Because the agent allows for glob-style syntax, it is possible to provide a configuration that enumerates a lot of files to tail at the same time, which can/will cause CPU spikes, and can also eat up all of the file descriptors allowed on the host (see #405).

Now, this information is kind of available via the logs already, but not in a very succinct way. You could analyze the agent log file for all of the info logs of the form `I! [logagent] piping log from %v/%v(%v) to %v with retention %v`, and just count all of the unique file names (the 4th param) in order to see how many files are being monitored, but is not super intuitive to do, and keeps the agent difficult to use/troubleshoot without intimate knowledge of what it's doing under the hood. 

---
Ideally this would work in a non-intrusive way. You shouldn't have to restart the agent or update configurations in order to see this debugging information. Luckily, the agent supports setting the debug log level via an environment variable, since #293 (released in v1.247350). So adding something that emits/logs how many files are being actively tailed should be pretty seamless. 

The first thing that comes to mind is adding that info to the internal profiler, but am open to other solutions. In `logs.go`, the `LogAgent` already keeps track of a map in memory, `destNames`, which maps a single tailed file to its destination (i.e.: `cloudwatchlogs`). The issue with the profiler is that it only allows metric addition, so if we added something rudimentary like `profiler.AddStats("num_logs_monitored", len(l.destNames))`, it would add that number to what is already in the profiler. The timing wouldn't match up - the log agent has a ticker with a 1 second frequency, but the profiler dumps metrics and clears on a 60 second frequency. As such, we would get 60x the real number with that approach.

**Comment by sethAmazon** [comment]
Maybe this can be at debug level. I don't think we need this at info since it will be more for debugging purposes.

**Comment by khanhntd** [comment]
For me, I would not suggest to use `destNames` since `AutoRemoval` will stop the tailers without removing the tailing files in the `destNames`. If we change that internal behavior it would be great since it reduces some [memory consumption](http://java-performance.info/memory-consumption-of-java-data-types-2/) so would be a great head up. For the alternative solution, needs some time to gather some thoughts.
