### ISSUE TITLE
What is CI_VERSION and where do we use it? (K8s daemonset)

### ISSUE THREAD

**Issue by alican63** [aws/amazon-cloudwatch-agent#435]
Hello everyone 👋 

I am looking at [k8s-yaml-templates](https://github.com/aws/amazon-cloudwatch-agent/blob/master/amazon-cloudwatch-container-insights/k8s-yaml-templates/cwagent-kubernetes-monitoring/cwagent-daemonset.yaml#L44-L45) and noticed that `CI_VERSION` is currently set to `k8s/1.3.9` 

Can anyone explain what `CI_VERSION` is? What does it do? I can't seem to find anything in cloudwatch source code

Would that be minimum supported kubernetes version or something?

Please clarify 🙏

**Comment by SaxyPandaBear** [comment]
`CI_VERSION` refers to the version of Container Insights: https://github.com/aws-samples/amazon-cloudwatch-container-insights. It doesn't refer explicitly to a version of k8s or anything. It is just semantic versioning for Container Insights. Hope that helps!

**Comment by SaxyPandaBear** [comment]
I just skimmed through the CloudWatch agent repo and the only references to `CI_VERSION` are inside the sample templates like the one you originally linked. AFAIK, these all got moved over to the aws-samples repo I referenced. You should be good to go.
