### ISSUE TITLE
Add a debug log in the ec2tagger plugin to indicate when it starts

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/amazon-cloudwatch-agent#463]
**Is your feature request related to a problem? Please describe.**
It is difficult to debug delays or latency in the ec2tagger processor plugin because the agent only emits a log when it completes initialization. If there is some error or delayed response in reaching out to IMDS, this isn't captured obviously. You would have to parse through the agent logs and have a good understanding of the plugin lifecycle in telegraf to connect the dots.

**Describe the solution you'd like**
Emit a debug log when we initialize the ec2tagger plugin, before the agent makes any network calls, so that it is easy to trace how long it takes to complete initialization of the processor.

**Describe alternatives you've considered**
People could gleam more information by setting the AWS SDK debug logging to log the actual request to IMDS, but that's not ideal because it bloats the log a lot when we can just get away with a single line code change. 

**Additional context**
An example of a scenario where it takes a long time to initialize the ec2tagger plugin
```
2022-03-31T09:16:19Z D! [agent] Initializing plugins
...
2022-03-31T09:20:19Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started, finished initial retrieval of tags and Volumes
2022-03-31T09:20:19Z D! [agent] Connecting outputs
2022-03-31T09:20:19Z D! [agent] Attempting connection to [outputs.cloudwatch]
```
You can see that telegraf starts initializing plugins at 9:16, but the log that indicates that the ec2tagger completed at 9:20, four minutes later. It is possible that there's something else in between that is the bottleneck, but we won't know until we add a log that lets us know that the agent started to init the ec2tagger.

**Comment by khanhntd** [comment]
This would be hard to work on since its modify the behavior of Go AWS SDK V1.
To be more specifically, we can replicate the issue by using the below manual test from John.
```
package main

import (
	"fmt"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/ec2metadata"
	"github.com/aws/aws-sdk-go/aws/session"
	"net/http"
	"time"
)

func main() {
	sess := session.Must(session.NewSession())

	hclient := &http.Client{Timeout: 1 * time.Minute}

	conf := aws.NewConfig().WithLogLevel(aws.LogDebugWithHTTPBody)

	conf.WithHTTPClient(hclient)

	emd := ec2metadata.New(sess, conf)

	fmt.Println("Before Available")
	emd.Available()

	fmt.Println("Available")
}
```

However, after running the below command in LXC Containers
```
root@databricks:~/helloaws# go run main.go
Before Available
2021/10/14 17:13:09 DEBUG: Request ec2metadata/GetToken Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go/1.41.2 (go1.17.2; linux; amd64)
Content-Length: 0
X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
Accept-Encoding: gzip


-----------------------------------------------------
2021/10/14 17:14:09 DEBUG: Request ec2metadata/GetToken Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go/1.41.2 (go1.17.2; linux; amd64)
Content-Length: 0
X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
Accept-Encoding: gzip


-----------------------------------------------------
2021/10/14 17:15:09 DEBUG: Request ec2metadata/GetToken Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go/1.41.2 (go1.17.2; linux; amd64)
Content-Length: 0
X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
Accept-Encoding: gzip


-----------------------------------------------------
2021/10/14 17:16:10 DEBUG: Request ec2metadata/GetToken Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go/1.41.2 (go1.17.2; linux; amd64)
Content-Length: 0
X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
Accept-Encoding: gzip


-----------------------------------------------------
2021/10/14 17:17:10 DEBUG: Request ec2metadata/GetMetadata Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /latest/meta-data/instance-id HTTP/1.1
Host: 169.254.169.254
User-Agent: aws-sdk-go/1.41.2 (go1.17.2; linux; amd64)
Accept-Encoding: gzip


-----------------------------------------------------
2021/10/14 17:17:10 DEBUG: Response ec2metadata/GetMetadata Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 19
Accept-Ranges: none
Content-Type: text/plain
Date: Thu, 14 Oct 2021 17:17:10 GMT
Last-Modified: Thu, 14 Oct 2021 16:48:47 GMT
Server: EC2ws


-----------------------------------------------------
2021/10/14 17:17:10 i-047c742b78a15ced6
Available
```

The result would be the 4 default retries with 1 minute timeout which has the same situation as our customers. However, this happens behind the `emd.Available` command, which Aws Sdk returns error but [tries to compress it](https://github.com/aws/aws-sdk-go/blob/40296143827033e447c2429dd0db906591e1a29f/aws/ec2metadata/api.go#L216). 

Therefore, my initial statements.
