### ISSUE TITLE
OTel Collector on Elastic Beanstalk not starting

### ISSUE THREAD

**Issue by msolli** [aws/amazon-cloudwatch-agent#483]
**Describe the bug**
When I try to start the OTel Collector on an Elastic Beanstalk instance, it does not start. The log contains the following lines:
```
2022/06/09 07:09:20 E! User aoc does not exist: no matching entries in passwd file
2022/06/09 07:09:20 E! Failed to ChangeUser: no matching entries in passwd file
2022/06/09 07:09:20 no matching entries in passwd file
```

**Steps to reproduce**
In an Elastic Beanstalk on the `Corretto 11 running on 64bit Amazon Linux 2/3.2.15` platform, do the following:

1. SSH to an instance using `eb ssh <env-name>`
2. `cd /opt/aws/amazon-cloudwatch-agent`
3. `sudo bin/amazon-cloudwatch-agent-ctl -a start -m ec2 -o default`

**What did you expect to see?**
I expected the OTel Collector to start with the default config.

**What did you see instead?**
The OTel Collector stopped immediately after emitting the log lines (see above).

This is the output of `sudo bin/amazon-cloudwatch-agent-ctl -a status`:

```
{
  "status": "running",
  "starttime": "2022-06-09T07:12:30+0000",
  "configstatus": "configured",
  "cwoc_status": "stopped",
  "cwoc_starttime": "",
  "cwoc_configstatus": "configured",
  "version": "1.247350.0"
}
```

**What version did you use?**
Version: 1.247350.0 (included with the Elastic Beanstalk platform)

**What config did you use?**
Config: the default (whatever is provided by `sudo bin/amazon-cloudwatch-agent-ctl -a start -m ec2 -o default`

**Environment**
OS: Amazon Linux 2/3.2.15
Elastic Beanstalk platform: Corretto 11 running on 64bit Amazon Linux 2/3.2.15

**Comment by SaxyPandaBear** [comment]
Thanks for bringing this up. We identified this as a regression in the version you called out, and just put out v1.247352 which addresses this. How are you installing the agent on Beanstalk? If you install the latest RPM from S3, you should be able to start the OTEL collector

**Comment by SaxyPandaBear** [comment]
I'm not sure how the agent gets included specifically for Beanstalk. It could be taken from S3 or it could be, in your case, taken directly from the Amazon Linux 2 YUM repository. If it's the latter, that still requires a release, which is a different process.

**Comment by msolli** [comment]
The agent comes pre-installed with the Amazon Linux that Elastic Beanstalk provides.

I've manually installed the latest version, and that worked. Thanks! I'll look into having it automatically installed from S3 on VM provisioning, at least until the Elastic Beanstalk team upgrades the platform with the latest agent.
