### ISSUE TITLE
Incorrect FQDN of Amazon CloudWatch endpoint

### ISSUE THREAD

**Issue by tornado-eyes** [aws/amazon-cloudwatch-agent#488]
**Describe the bug**
After installation, I keep getting the following error: I looked closely at the logs and noticed that the Amazon CloudWatch endpoint name was misspelled. In this state, the request to the Amazon CloudWatch endpoint always fails.
- Correct: monitoring.ap-northeast-1.amazonaws.com
- In fact: monitoring.ap-norteast-1.amazonaws.com

amazon-cloudwatch-agent.log:
2022-06-14T12:42:54Z E! cloudwatch: code: RequestError, message: send request failed, original error: Post "https://monitoring.ap-norteast-1.amazonaws.com/": dial tcp: lookup monitoring.ap-norteast-1.amazonaws.com on 172.26.0.2:53: no such host
2022-06-14T12:42:54Z W! 160 retries, going to sleep 1m0s before retrying.
2022-06-14T12:42:54Z E! WriteToCloudWatch failure, err:  RequestError: send request failed
caused by: Post "https://monitoring.ap-norteast-1.amazonaws.com/": dial tcp: lookup monitoring.ap-norteast-1.amazonaws.com on
 172.26.0.2:53: no such host
2022-06-14T12:43:54Z E! WriteToCloudWatch failure, err:  RequestError: send request failed
caused by: Post "https://monitoring.ap-norteast-1.amazonaws.com/": dial tcp: lookup monitoring.ap-norteast-1.amazonaws.com on
 172.26.0.2:53: no such host
2022-06-14T12:43:54Z E! WriteToCloudWatch failure, err:  RequestError: send request failed
caused by: Post "https://monitoring.ap-norteast-1.amazonaws.com/": dial tcp: lookup monitoring.ap-norteast-1.amazonaws.com on
 172.26.0.2:53: no such host

**Steps to reproduce**
Occurs at intervals set after installation and setting by executing the following command.
1.wget https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
2.sudo dpkg -i -E ./amazon-cloudwatch-agent.deb
3.sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard
4.sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -s -m onPremise -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json

**What did you expect to see?**
Use CloudWatch Agent to monitor my Lightsail instance's disk and memory metrics.
[https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-monitor-with-cloudwatch/?nc1=h_ls](https://aws.amazon.com/premiumsupport/knowledge-center/lightsail-monitor-with-cloudwatch/?nc1=h_ls)

**What did you see instead?**
The logs were not reflected in the Amazon CloudWatch console, and I found a connection failure error to the Amazon CloudWatch endpoint in the following logs.
amazon-cloudwatch-agent.log:
cloudwatch: code: RequestError, message: send request failed, original error: Post "https://monitoring.ap-norteast-1.amazonaws.com/": dial tcp: lookup monitoring.ap-norteast-1.amazonaws.com on 172.26.0.2:53: no such host

**What version did you use?**
https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
Version: Amazon CloudWatch Agent 1.247352.0 (2022-05-26)
aws-cli/2.6.3 Python/3.9.11 Linux/4.19.0-20-cloud-amd64 exe/x86_64.debian.10 prompt/off

**What config did you use?**
Config: the agent json config file
/opt/aws/amazon-cloudwatch-agent/bin/config.json
{
    "agent": {
        "metrics_collection_interval": 60,
        "run_as_user": "root"
    },
    "metrics": {
        "metrics_collected": {
            "cpu": {
                "measurement": [
                    "cpu_usage_idle",
                    "cpu_usage_iowait"
                ],
                "metrics_collection_interval": 60,
                "totalcpu": true
            },
            "disk": {
                "measurement": [
                    "used_percent"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                    "*"
                ]
            },
            "diskio": {
                "measurement": [
                    "io_time",
                    "write_bytes",
                    "read_bytes",
                    "writes",
                    "reads"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                    "*"
                ]
            },
            "mem": {
                "measurement": [
                    "mem_used_percent"
                ],
                "metrics_collection_interval": 60
            },
            "net": {
                "measurement": [
                    "bytes_sent",
                    "bytes_recv",  
                    "packets_sent",
                    "packets_recv"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                    "*"
                ]
            },
            "swap": {
                "measurement": [
                    "swap_used_percent"
                ],
                "metrics_collection_interval": 60
            }
        }
    }
}

**Environment**
OS: Debian 10
Package Version: Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
(using Lightsail)

**Additional context**
I think it will work if the endpoints are fixed correctly, but if it's an environmental issue please comment.

**Comment by khanhntd** [comment]
Hey @tornado-eyes ,
Please share with us the region you have set through `aws configure` or ensure your region is not `ap-norteast-1` CloudWatchAgent creates the session from the environment (which belongs to the SDK); therefore, it is not an encoded/fixed endpoint.

**Comment by tornado-eyes** [comment]
Thank you for your response. I understand the content. Thank you very much. I apologize for the inconvenience. Please close it.
