### ISSUE TITLE
Downloading non-latest version

### ISSUE THREAD

**Issue by paololazzari** [aws/amazon-cloudwatch-agent#503]
I'm working on a versioned build, therefore I don't want to be downloading the "latest".

All of the instructions only show how to download the latest from S3.
How can I download non-latest versions from S3?

**Comment by paololazzari** [comment]
I'm building a virtual machine with Packer. For all of the other software that I am installing, I am using versioned artefacts so that the build will be reproducible going forward. I would like to do the same for the cloudwatch agent

**Comment by Alex-Waring** [comment]
Can I request that this is re-opened please, @zhihonl you might be able to do that for me. In production and regulated environments, reproducible builds are critical so we need to be able to select a version.
