### ISSUE TITLE
Update aws-otel-collector to later version to fix HIGH severity issue for containerd

### ISSUE THREAD

**Issue by andypaterson40** [aws/amazon-cloudwatch-agent#515]
Currently install the CW agent on custom containers but when we run the AWS Inspector report against the completed containers - we receive quite a few HIGH severity issues. Most of them are related to old containerd version (v1.4.4). Upon closer inspection, we can see that the CW agent from this repo is using using aws-otel-collector v0.11.0 which uses containerd v1.4.4
Fix is to use later version of containerd v1.5 or v1.6. I have noticed that aws-otel-colelctor repo latest versions of v0.18 and v0.19 use latest versions of containerd.

So is it possible to update the aws-otel-collector to use near latest version?

I'm trying to build and run locally this repo but having some issues at the moment which i'm working through. Just wondering if the package can be updated in the meantime.

**Comment by SaxyPandaBear** [comment]
Thanks for calling this out. We've actually removed the adot package from the CWAgent installable, so I think that this ask is moot now. Feel free to reopen if there are still questions.
