### ISSUE TITLE
CW Agent does not appear to acknowledge AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

### ISSUE THREAD

**Issue by kory** [aws/amazon-cloudwatch-agent#572]
We're trying to get an AWS Cloudwatch Agent running in our Ubuntu docker container running on ECS.

In my env on ECS, `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is set, and other processes are using it successfully. I do not have a credential file. Per the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default), `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` should be read periodically for the correct CloudWatch access credentials.

Instead, when I run `/opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent`, I see `will use file based credentials provider`. The agent proceeds to exclusively try to read a credentials file rather than reading the env URL above. 

Is there some setting I am missing, or does CW Agent not read the above environment variable? If it does not, could it be updated to read these credentials per the above link?

It looks like a similar question was asked in https://github.com/aws/amazon-cloudwatch-agent/issues/140, but it appears to have been closed without acknowledging support for the above method to retrieve credentials. Is the above credential flow not supported? Hoping to get clarity here.

Thank you!

**Comment by SaxyPandaBear** [comment]
How are you getting the agent on the container? Are you using your own Dockerfile to get the agent and install/run it?

**Comment by kory** [comment]
I'm using my own dockerfile to install the agent:

```
# Cloudwatch agent
RUN wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
RUN apt install ./amazon-cloudwatch-agent.deb
RUN rm amazon-cloudwatch-agent.deb
```

I actually seem to be hitting this issue:
https://github.com/aws/amazon-cloudwatch-agent/issues/118
If I force the CW agent to act like it's running on EC2, it seems to pick up the environment successfully. But by default on ECS Fargate, it does not.

**Comment by sethAmazon** [comment]
Why do you not run in ecs fargate how our samples works?

**Comment by ajit-kolathur** [comment]
Try adding the following ENV variable to your docker image. It worked for me
```
ENV RUN_IN_AWS="True"
```
