### ISSUE TITLE
Missing data points in metrics.

### ISSUE THREAD

**Issue by ejgomezweekendesk** [aws/amazon-cloudwatch-agent#575]
**Describe the bug**
Currently, we are experiencing 'gaps' in our metrics, due to missing data. The agent is requesting data at the configured interval correctly.
However, it seems to be ignoring some request, generating  traces like `E! metric_type ERROR: jvm_memory_used_bytes|cwagent-ecs-file-sd-config|10.1.11.129:80|`.
This end up producing gaps in our metrics of up to 20 minutes sometimes.

The output from our metrics endpoint is as follow:
```
# HELP jvm_memory_used_bytes The amount of used memory
# TYPE jvm_memory_used_bytes gauge
jvm_memory_used_bytes{area="heap",id="Tenured Gen",} 2.87002624E8
jvm_memory_used_bytes{area="heap",id="Eden Space",} 1.38661728E8
jvm_memory_used_bytes{area="nonheap",id="Metaspace",} 1.03324624E8
jvm_memory_used_bytes{area="nonheap",id="Code Cache",} 3.566944E7
jvm_memory_used_bytes{area="heap",id="Survivor Space",} 5531056.0
jvm_memory_used_bytes{area="nonheap",id="Compressed Class Space",} 1.2479872E7
```
We are unsure if is a formatting problem.

**Comment by khanhntd** [comment]
Interesting ! Based on the error you given us, the CWAgent with Prometheus Input Plugin is not able to determine the type for those metrics when [scraping from metadata store based on target and job instance](https://github.com/khanhntd/amazon-cloudwatch-agent/blob/8c0b7e1244eefa36f7d5681550e9456e67fee233/plugins/inputs/prometheus_scraper/metrics_type_handler.go#L68-L70).  Therefore, please send us :
* Prometheus configuration
* CWAgent configuration
