### ISSUE TITLE
Event Rule is failing to log event in target CloudWatch group on env

### ISSUE THREAD

**Issue by nick-rossi** [aws/amazon-cloudwatch-agent#576]
I have a cloudformation.yaml file which builds infrastructure on 4 envs (sandbox, dev, staging, prod) when deployed. What's happening is my AWS::Events::Rule is triggered by a batch job when the status is changed to `FAILED`. This works fine on sandbox but not on dev for some reason. Which is strange behavior because it's all sourced from one cloudformation.yaml file.

**What did you expect to see?**
A Batch event in cloudwatch logs when a batch job has failed.

**What did you see instead?**
No logs appeared in cloudwatch logs group target.

**What config did you use?**
Config: cloudformation.yaml

CloudFormation code:
```
 # AWS Batch - log group
  BatchFailuresEventsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/events/batch/${pEnvironment}-batch-failures-events-logs
      RetentionInDays: 14

  # Event Rule for Batch job failures
  BatchFailuresEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Send event to log group when a Batch job status is FAILED"
      Name: !Sub "${pEnvironment}-batch-failure-events-rule"
      EventPattern:
        source:
          - "aws.batch"
        detail-type:
          - "Batch Job State Change"  # Set value, this is not a custom string
        detail:
          status:
            - "FAILED"
      Targets:
        - 
          Id: BatchFailuresEventsLogGroup
          Arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/events/batch/${pEnvironment}-batch-failures-events-logs"

 # Allow failed batch events access to BatchFailuresEventsLogGroup
  BatchFailuresEventsResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "BatchJobEventsLogGroupPolicy"
      PolicyDocument: "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Sid\": \"TrustEventsToStoreLogEvent\", \"Effect\": \"Allow\", \"Principal\": { \"Service\": [ \"events.amazonaws.com\", \"delivery.logs.amazonaws.com\" ] }, \"Action\": [ \"logs:CreateLogStream\", \"logs:PutLogEvents\", \"logs:CreateLogGroup\" ], \"Resource\": \"arn:aws:logs:::log-group:/aws/events/batch/*:*\" } ] }"
```

**Comment by SaxyPandaBear** [comment]
Hey @nick-rossi thanks for reaching out. Just to be sure, are you using the CloudWatch agent to send logs? It looks like you are using AWS EventBridge to facilitate sending logs to the log group from the AWS Batch job, which isn't really related to the CloudWatch agent. If that's the case, I don't think this is the right forum to get insight on your issue. 

Are your environments in the same AWS account? Maybe there's a conflict there when creating the CloudFormation stacks and it's somehow being routed from the dev batch job to the sandbox log group? Not really sure. Also maybe a dumb question, but this only matches failed batch jobs, so was there a specific batch job failure in the dev environment that would confirm the integration?

**Comment by nick-rossi** [comment]
Hi @SaxyPandaBear thanks for the clarification that is correct. The cloudwatch group is the target not where the events are originating from. Which forum would be correct to post this on?

Also envs are not on the same account I have checked those possible reasons. And yes the batch job looks for generic failures so any failure event should be appearing in the target logs.

**Comment by SaxyPandaBear** [comment]
@nick-rossi I think that reaching out to AWS Support via the AWS console might be your best bet since they'll be better equipped to troubleshoot with you.

**Comment by SaxyPandaBear** [comment]
Closing this as it's not pertinent to the CloudWatch agent
