### ISSUE TITLE
Prometheus scrape - too many metrics are sent to CloudWatch 

### ISSUE THREAD

**Issue by oridool** [aws/amazon-cloudwatch-agent#592]
**Describe the bug**
I'm running the agent (image version  amazon/cloudwatch-agent:1.247355.0b252062 ) on EKS, and using it for scraping custom Prometheus metrics of my application, and send them to CloudWatch.
I'm only interested in few custom metrics to be sent to CW, although my application's prometheus endpoint exposes many more.
I've configured the selected metrics in the configuration file cwagentconfig.json (under `logs.metrics_collected.prometheus.emf_processor.metric_declaration`).
  
I can see the configured metrics in CloudWatch metrics under `ContainerInsights/Prometheus` (which is working as expected).
However, when I look in the CW log group, I see all the logs of the other Prometheus metrics of my application, even those that were not configured under `emf_processor.metric_declaration`.

**Steps to reproduce**
Here is the configuration yaml , with the specified metrics for the `events-service` job:

<details>
<summary>configmaps</summary>

```
# create configmap for prometheus cwagent config
apiVersion: v1
data:
  # cwagent json config
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "prometheus": {
            "prometheus_config_path": "/etc/prometheusconfig/prometheus.yaml",
            "emf_processor": {
              "metric_declaration": [
                {
                  "source_labels": ["job"],
                  "label_matcher": "events-service",
                  "dimensions": [["ClusterName","Namespace","application"]],
                  "metric_selectors": [
                    "^rabbitmq_channels$",
                    "^policycoverage_active_reports$"
                  ]
                },
                {
                  "source_labels": ["job"],
                  "label_matcher": "events-service",
                  "dimensions": [["ClusterName","Namespace","application","pool"]],
                  "metric_selectors": [
                    "^hikaricp_connections_creation_seconds_sum$"
                  ]
                }								
              ]
            }
          }
        },
        "force_flush_interval": 5
      }
    }
kind: ConfigMap
metadata:
  name: prometheus-cwagentconfig
  namespace: amazon-cloudwatch

---
# create configmap for prometheus scrape config
apiVersion: v1
data:
  # prometheus config
  prometheus.yaml: |
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
    scrape_configs:
    - job_name: 'events-service'
      sample_limit: 10000
      metrics_path: /actuator/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_container_port_name]
        action: keep
        regex: eventsservice;metrics
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: Namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: pod_controller_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_controller_kind
        target_label: pod_controller_kind
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_phase
        target_label: pod_phase

kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: amazon-cloudwatch

---

``` 
</details>

**What did you expect to see?**
Under the CW log group `/aws/containerinsights/<eks-cluster-name>/prometheus` and stream `events-service` , I was expecting to see only logs related to the metrics that I've configured in cwagentconfig.json.

**What did you see instead?**
I saw other metrics of my application, other than the only 3 I have configured.
Which means that I'm paying for data that I don't really use.

**What version did you use?**
Version: 1.247355.0b252062 

**What config did you use?**
The configuration is written above

**Environment**
EKS 1.22

**Comment by prm-james-hill** [comment]
I'm still seeing this in amazon/cloudwatch-agent:1.300028.1b210

**Comment by eugen-eugen** [comment]
The issue is still there. After some research, i would say, that the parameter logs.metrics_collected.prometheus.emf_processor.metric_declaration.metric_selectos is not respected at all in the code of cloudwatch agent.

**Comment by wjrogers** [comment]
Will a maintainer please consider re-opening this issue? I was surprised and confused to find metrics not matched by a `metric_selectors` item appear in my CloudWatch logs. I am running agent version 1.300064.1b1344.
