### ISSUE TITLE
prefix "file_" is added anytime you run fetch-config.

### ISSUE THREAD

**Issue by emper0r** [aws/amazon-cloudwatch-agent#594]
**Describe the bug**
Hi i'm trying to automate with ansible configuration of cloudwatch agent, according of the documentation https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html 

Following doc and save it the file into ` /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json` and run the command: `amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json` the config is valid and service is started **BUT** the configuration file is deleted it !.
So for automation this isn't ok because I need the file to next time for ansible know if was changed to verify idempotency for automation.

Doing other research I see under` /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_amazon-cloudwatch-agent.json` when I repeat the command above I saw that file never delete it and have the same configuration I set before, so i guess the first situation was move the file into that directory setting the prefix **file_** behind.
so I can use this for idempotency for ansible **BUT** the `fetch-config `again do another behaivor recreating the same file putting twice **file_** as prefix so at the end of the day I got

from: **file_amazon-cloudwatch-agent.json** to this: **file_file_amazon-cloudwatch-agent.json**

**Steps to reproduce**
create any simple configuration in json and put the file under directory: `/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/amazon-cloudwatch-agent.json`

then run:
```
ls
amazon-cloudwatch-agent.json

amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/amazon-cloudwatch-agent.json

ls
file_amazon-cloudwatch-agent.json

amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_amazon-cloudwatch-agent.json

ls
file_file_amazon-cloudwatch-agent.json

amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_file_amazon-cloudwatch-agent.json

ls
file_file_file_amazon-cloudwatch-agent.json

```
and so on....

**What did you expect to see?**
fetch-config must be fetch configuration and NOT rename adding more prefix **file_** to the same file.

**What did you see instead?**
renaming the file adding prefix **file_**

**What version did you use?**
```
rpm -qa | egrep agent
amazon-cloudwatch-agent-1.247355.0b252062-1.x86_64

```

**What config did you use?**
**file:** amazon-cloudwatch-agent.json
**directory:** /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/
```
{
  "agent": {
    "metrics_collection_interval": 60,
    "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
    "run_as_user": "root"
  },
  "logs": {
    "logs_collected": {
      "files": {
      "collect_list": [{
          "file_path": "/var/log/secure",
          "log_group_name": "secure",
          "log_stream_name": "{instance_id}",
          "retention_in_days": 1
        }]
      }
    }
  },
  "metrics": {
    "aggregation_dimensions": [
      [
        "AutoScalingGroupName"
      ],
      [
        "ImageId"
      ],
      [
        "InstanceId"
      ],
      [
        "InstanceType"
      ]
    ],
    "append_dimensions": {
      "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
      "ImageId": "${aws:ImageId}",
      "InstanceId": "${aws:InstanceId}",
      "InstanceType": "${aws:InstanceType}"
    },
    "metrics_collected": {
                                          "swap": {
        "measurement": [
          "swap_used",
          "swap_used_percent"
        ],
        "metrics_collection_interval": 60
      }
    }
  }
}

```

**Environment**
OS: Almalinux 8.6

**Additional context**
No.

**Comment by SaxyPandaBear** [comment]
Just chiming in, you should NOT rely on files in the `etc/amazon-cloudwatch-agent.d/` directory. This is used by the agent internally.

**Comment by emper0r** [comment]
Hi @SaxyPandaBear 

ok.. so how can I check if the original .json was different to know if some parameter was changed after fetch-config take the json and delete it?, this thing not happen with Windows agent. in fact Windows leave the json file. in that case the automation is fine.

**Comment by emper0r** [comment]
@SaxyPandaBear the diff is an action created by ansible task that's not the problem here.
the real situation here is, 

why the json file after fetch-config is deleted ? is normal that ? 

if i put 

file: `amazon-cloudwatch-agent.json` into 
directory: `/opt/aws/amazon-cloudwatch-agent/etc/`
and then run: `amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json`

after command end runs the file is delete it. and I need to know if that is normal because a I need that file the next time like windows does, use the file for configurate agent and then leave the file there, without erease it.

**Comment by varshashesh** [comment]
I have seen this issue as well. 
The file_config.json should not be renamed every time we run fetch-config

**Comment by emper0r** [comment]
Hi, just for update.
Meanwhile this is solve I use as workaround re-coping again the config after reload and agent delete the file to get it again for the next ansible run and check out for idempotency automation.

**Comment by SaxyPandaBear** [comment]
I can look into it more. I think there's a gap somewhere here. I know that when I test the agent, the json config persists on disk but it might be an issue of where the config is located. If you use the wizard, it outputs to `/opt/aws/amazon-cloudwatch-agent/bin/config.json`. In my latest testing, I've just put it in `/home/ec2-user/config.json`. In both of these cases, the JSON file does not get deleted.

**Comment by emper0r** [comment]
oh ok... then i'll test using one of that explicit paths...

**Comment by emper0r** [comment]
yes. I can confirm.. now works fine with automation ansible. thanks @SaxyPandaBear.

**Comment by martinamunoz** [comment]
I can confirm that if the file is located at /home/ec2-user/config.json then will not be deleted
