### ISSUE TITLE
"retention_in_days" and creation of log-streams potentially does not work

### ISSUE THREAD

**Issue by Skyrant** [aws/amazon-cloudwatch-agent#620]
**Describe the bug**
CWA allows "retention_in_days" to be set for each item in the "collect_list". Configuration json file is in Parameter Store. If multiple log-files are configured only the first one has the retention set correctly in the translated toml file. Only the first log-stream is created in the  CW log-group.

**Steps to reproduce**
Create a Json config with 2 log files and retention other than -1. Store the json in Parameter Store. Use AWS Systems Manager to run AmazonCloudWatch-ManageAgent -> configure to Configure the CWA using the Parameter Store.

**What did you expect to see?**
I expected retention_in_days to get set for my log groups, a log group created, and all log-streams created.

**What did you see instead?**
Retention was only changed on first log-file, all others were set to -1 (default = never expire). Only the first log-stream was created.

**What version did you use?**
CWAgent/1.247354.0b251981 (go1.18.3; linux; amd64) 2022-07-22T13:38:57+0000

**What config did you use?**
```...
"logs": {
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/tmp/foo.log",
						"log_group_name": "foo",
						"log_stream_name": "{instance_id}-foo",
                                                "timestamp_format": "%Y-%m-%d %H:%M:S,%f",
                                                "multi_line_start_pattern": "{timestamp_format}",
						"retention_in_days": 90
					},
					{
						"file_path": "/tmp/bar.log",
						"log_group_name": "foo",
						"log_stream_name": "{instance_id}-bar",
                                                "timestamp_format": "%Y-%m-%d %H:%M:S,%f",
                                                "multi_line_start_pattern": "{timestamp_format}",
						"retention_in_days": 90
					}
				]
			}
		}
	}
...
```
**Environment**
Linux version 4.14.256-197.484.amzn2.x86_64 (mockbuild@ip-10-0-37-156) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC)) #1 SMP Tue Nov 30 00:17:50 UTC 2021

**Additional context**
This was on the first configure run. The log group did not exist yet.

**Comment by Skyrant** [comment]
Additional:
The log streams have been created after some time. The retention is still set to -1.

**Comment by SaxyPandaBear** [comment]
So I looked into it and confirmed that the bug fix for this hasn't been released yet. We're kicking off the release process today and estimate it will be globally available in about 3 weeks. Thanks for bringing this to our attention

**Comment by Skyrant** [comment]
Thanks!

**Comment by SaxyPandaBear** [comment]
Update on this: we are just now starting the release process. Sorry for the delay. In review, we backed out some changes that aren't ready yet - covered in #632 

So I can more closely say 3 weeks from **now**. Again, apologies for the delay.

**Comment by adam-mateen** [comment]
v1.247357 release is in progress.
The global S3 link has been updated, and some of the regional links as well.
The full release process will be complete within 1-2 weeks.
