### ISSUE TITLE
GitHub Actions integration tests creates orphaned IAM roles in AWS account

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/amazon-cloudwatch-agent#629]
I just deleted 200 ECS integration task roles from my AWS account. All of which were created from the ECS integration test. These should be cleaned up, either by deleting the roles as part of the Terraform destroy, or by (1) tagging the integration test IAM roles, then (2) using another GHA resource cleaner (like the AMI and instance cleaner) to delete unused old roles.

**Comment by khanhntd** [comment]
I believe this will address the issue https://github.com/aws/amazon-cloudwatch-agent-test/pull/70. The only action left for us is to clean up all the resources.
