### ISSUE TITLE
GPU metrics support on ContainerInsights

### ISSUE THREAD

**Issue by ryansteakley** [aws/amazon-cloudwatch-agent#634]
**Is your feature request related to a problem? Please describe.**
GPU metrics are not support when using Container-insights even when modifying the config file. It would be nice to have GPU metric support when using ContainerInsights

Similar to the way ContainerInsights currently grabs the metrics from the EKS clusters underlying EC2 nodes it would be nice if this would work for GPU nodes and their gpu metrics. The issue currently is that when you specify to collect NVIDIA_GPU metrics, the error message will complain that nvidia_smi is not installed as the aws-nodes when you exec into them using kubectl exec do not contain nvidia_smi. However the ec2 node that is represented by that aws-node itself does have the nvidia-smi installed. 

**Describe the solution you'd like**
For Container-insights to support GPU metrics similiar the way it does CPU metrics.
**Describe alternatives you've considered**

**Additional context**

These gpu nodes were created using eksctl and its default gpu node creation.

**Comment by PrivoSteve** [comment]
I spoke with an AWS support engineer and he told me that this is a feature that will be added in the future but he could not tell me when.  We can only wait.

One solution would be to use a userdata script and install the cloudwatch agent directly on the node itself when it launches and configure the config file to collect the gpu metrics (per the AWS docs).  This does actually work but only for AL2 instances.  This will not work on BottleRocket instances.

**Comment by amodsachintha** [comment]
Thanks for your comment. I wrote a python script to collect and send GPU stats to Cloudwatch and it's running inside a `cuda` docker image. It's deployed as a daemonset within EKS. Time was not on my side so I had to resort to this, but it works perfect.
