### ISSUE TITLE
Agent should emit logs when deleting log files with auto_removal feature

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/amazon-cloudwatch-agent#636]
https://github.com/aws/amazon-cloudwatch-agent/blob/dc6be64b5bf64982f1dd00af3deb64ffb64855dd/plugins/inputs/logfile/tailersrc.go#L278-L282

The above lines show what logging is present right now for `auto_removal`. It only logs something if the agent **fails** to delete the log file. But there's no indication for successfully deleting the log file. This makes it confusing because you can't know for sure that the agent deleted the log file, or if something else (host-level log rotation?) deleted the log file before the agent does.

**Comment by khanhntd** [comment]
Thanks @pradeepnnv. Let's us know if there is any thing we could help you advance your obj
