### ISSUE TITLE
Use nanoseconds instead of milliseconds

### ISSUE THREAD

**Issue by epapbak** [aws/amazon-cloudwatch-agent#650]
**Is your feature request related to a problem? Please describe.**
Due to the usage of milliseconds as a time unit, we end up seeing this a lot of times when using multiple pods for a service:
`could not write event: InvalidParameterException: Log events in a single PutLogEvents request must be in chronological order.`

**Describe the solution you'd like**
Use nanoseconds precision instead of milliseconds

**Describe alternatives you've considered**
N/A

**Additional context**
Cloudwatch works amazingly when used with a couple of pods, but production-grade deployments sometimes send too much logs.

**Comment by SaxyPandaBear** [comment]
That would be great, but unfortunately I think we're constrained to what the CloudWatch Logs API lets us provide. The PutLogEvents API expects something with millisecond precision: https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_InputLogEvent.html

> The time the event occurred, expressed as the number of milliseconds after Jan 1, 1970 00:00:00 UTC

**Comment by SaxyPandaBear** [comment]
If you're using the CloudWatch agent, I could see potentially filtering undesirable logs with the log filter feature. Not sure if that helps. https://github.com/aws/amazon-cloudwatch-agent#log-filtering

**Comment by epapbak** [comment]
Didn't know about the log filtering. It does not help in this scenario, but thanks for mentioning it.
I'm closing the issue then.
