### ISSUE TITLE
Document how to have CloudWatch Agent listen on `0.0.0.0`

### ISSUE THREAD

**Issue by pb8o** [aws/amazon-cloudwatch-agent#654]
**Describe the bug**

Missing documentation on how to have CloudWatch Agent listen on `0.0.0.0`

**Steps to reproduce**

The default configuration listens on `127.0.0.1:25888`

**What did you expect to see?**

```sh
% ss -ltu
udp               UNCONN             0                   0     *:25888                                              *:*
```

The default is good and safe, but there should be a documented way of listening on `0.0.0.0`

**What did you see instead?**

```sh
% ss -ltu
udp               UNCONN             0                   0     127.0.0.1:25888                                              *:*
```

**What version did you use?**
Version: `1.247356.0b252264`

**What config did you use?**
Config: (e.g. the agent json config file)

```json
{"logs": {"metrics_collected": {"emf": {}}}}
```

**Environment**
OS: AL2

**Additional context**

**Comment by taohungyang** [comment]
Hi @pb8o, you should be able to specify the service address (and protocol) like this
https://github.com/aws/amazon-cloudwatch-agent/blob/24420d86d387bfd21b7f12f53c551fd5c5291061/translator/totomlconfig/sampleConfig/complete_linux_config.json#L172-L175
Can you try and see if this works for your case?

**Comment by pb8o** [comment]
Hi @taohungyang! Thanks for the quick response. I will try that next. Is it possible to specify both TCP and UPD as in the default?

**Comment by taohungyang** [comment]
I don't think the current translator let you put multiple service addresses. I don't know what the reason was but it could be because the [socket_listner](https://github.com/aws/telegraf/tree/aws-cwa-release-1-23-0/plugins/inputs/socket_listener) (the input plugin in this case) only let us specify one service address per input plugin

**Comment by pb8o** [comment]
I tried and it works! Thank you for the quick response. Is this documented somewhere I have missed?

Re: the multiple listeners, we don't immediately need it, but it would be nice to be able to replicate the default config of listening both in TCP and UDP.

**Comment by taohungyang** [comment]
Glad to hear it solved the issue. I checked the guide of manually configuration and seems like this is a miss. I'll work with people to update that doc.
