### ISSUE TITLE
Latest version doesn't match the version that is supplied from AWS package download

### ISSUE THREAD

**Issue by adespain** [aws/amazon-cloudwatch-agent#656]
**Describe the bug**
When I download the .deb package here:  https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb it is version 1.247356, but github shows the latest as 1.247355, is there a reason why the latest versions are different?
**Steps to reproduce**
Just download the .deb file and install it and check the status, it will show the version which is 1.247356, whereas the github latest tag shows 1.247355
**What did you expect to see?**
I was expecting the versions for latest to be the same.
**What did you see instead?**
I see the versions are different with regards to the latest tag.
**What version did you use?**
Version: (e.g., `v1.247350.0`, etc)

**What config did you use?**
Config: (e.g. the agent json config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
ubutnu 20.04
**Additional context**

**Comment by SaxyPandaBear** [comment]
The "release" tagging on GitHub is done manually so it could be missed while rolling out. I think that the release notes get published automatically on S3 alongside the installer artifacts but I don't remember where.

**Comment by adam-mateen** [comment]
I just updated the release page:
https://github.com/aws/amazon-cloudwatch-agent/releases

With v1.247356 and v1.247357 using the auto generated release notes feature of github.
There is also a RELEASE_NOTES file in this repository which filters out changes which are probably not interesting to users.

Please note that v1.247357 is currently being released so while the global S3 link returns this package, a regional link might not for the next week or so.

**Comment by adespain** [comment]
looks like the github latest version is ahead of the s3 package again, just confirmed this by downloading the .deb file and it is version 1.247356...so maybe it doesn't get updated for more than a few weeks?

**Comment by SaxyPandaBear** [comment]
What link did you use? I just spot checked Amazon Linux 2, and it was v1.247357. Spinning up an Ubuntu host to spot check the ubuntu link you posted in the original issue

**Comment by SaxyPandaBear** [comment]
```
ubuntu@ip-172-31-21-62:~$ wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
--2023-01-09 20:52:30--  https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.40.0, 52.216.77.38, 52.216.184.93, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.40.0|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39187078 (37M) [application/octet-stream]
Saving to: ‘amazon-cloudwatch-agent.deb’

amazon-cloudwatch-agent.deb                          100%[=====================================================================================================================>]  37.37M  6.37MB/s    in 6.3s    

2023-01-09 20:52:37 (5.95 MB/s) - ‘amazon-cloudwatch-agent.deb’ saved [39187078/39187078]

ubuntu@ip-172-31-21-62:~$ sudo dpkg -i amazon-cloudwatch-agent.deb 
Selecting previously unselected package amazon-cloudwatch-agent.
(Reading database ... 63919 files and directories currently installed.)
Preparing to unpack amazon-cloudwatch-agent.deb ...
create group cwagent, result: 0
create user cwagent, result: 0
Unpacking amazon-cloudwatch-agent (1.247357.0b252275-1) ...
Setting up amazon-cloudwatch-agent (1.247357.0b252275-1) ...
```

**Comment by adespain** [comment]
@SaxyPandaBear Hmm, thanks for that, I am behind a proxy so maybe that is my issue.  I'll do some more research.
