### ISSUE TITLE
Invalid mode error

### ISSUE THREAD

**Issue by adespain** [aws/amazon-cloudwatch-agent#657]
**Describe the bug**
After installing and trying to start the agent I get an error:

```
Invalid mode auto.  Valid mode values are ec2, onPrem and onPremise. panic: Invalid mode auto. Valid mode values are ec2, onPrem and on Premise
```

**Steps to reproduce**
download and install the .deb file from here:  https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

**What did you expect to see?**
I expected it to run without errors.
**What did you see instead?**
I saw the error above.
**What version did you use?**
Version: v1.247356.0b252264

The previous version v1.247355 works however...

**What config did you use?**
Config:  the agent json config file

**Environment**
OS: Ubuntu 20.04

**Additional context**

**Comment by SaxyPandaBear** [comment]
Hey, thanks for reporting this. This is a known issue and the team is working on rolling out a fix globally

**Comment by SaxyPandaBear** [comment]
Looping back to this, v.1247357 should be released globally which fixes this issue.
