### ISSUE TITLE
Multiple clusters defined in sd_target_cluster 

### ISSUE THREAD

**Issue by sergiocharpineljr** [aws/amazon-cloudwatch-agent#661]
**Is your feature request related to a problem? Please describe.**
I need to scrape metrics from different ECS clusters from a single agent. `sd_target_cluster` only allows one cluster. Also I can't provide multiple `prometheus` or `ecs_service_discovery` configurations in a single agent.

**Describe the solution you'd like**
`sd_target_cluster` could be a regex or a array of strings.
```
{
    "logs": {
        "metrics_collected": {
            "prometheus": {
                "ecs_service_discovery": {
                    "docker_label": {},
                    "sd_cluster_region": "us-east-1",
                    "sd_frequency": "1m",
                    "sd_result_file": "cwagent_ecs_auto_sd.yaml",
                    "sd_target_cluster": "clusters-a.*" # or a array
                },
                "log_group_name": "NotApplicable"
            }
        }
    }
}
```
**Describe alternatives you've considered**
Configuring multiple agent instances.

**Additional context**

**Comment by Nexus2k** [comment]
Wierdly enough the readme.md file already mentioned this feature: https://github.com/aws/amazon-cloudwatch-agent/blob/main/internal/ecsservicediscovery/README.md#configuration-example
But when trying to use that config (well preferably by not providing a cluster name at all) the agent complains.

**Comment by GregBo7** [comment]
I'm trying to add multiple cluster on a single agent too. No way to do that, the property in documentation sd_target_cluster**s** not exists.
