### ISSUE TITLE
Make the packages relocatable or be able to have multiple namespaces in same config.

### ISSUE THREAD

**Issue by herrsergio** [aws/amazon-cloudwatch-agent#674]
**Is your feature request related to a problem? Please describe.**
Execute 2 or more CloudWatch agents, right now, it is not possible to define multiple namespaces in an agent configuration.

**Describe the solution you'd like**
Be able to indicate where to install the CloudWatch agent. (/opt is hardcoded)

**Describe alternatives you've considered**
I tried to install a different agent in another location, but internally it is still looking to /opt/aws/amazon-cloudwatch-agent-memory/bin/start-amazon-cloudwatch-agent

**Additional context**
Need to have multiple namespaces or be able to execute multiple agents.

**Comment by SaxyPandaBear** [comment]
Hey there! Can you explain your use case for running multiple instances of the CloudWatch agent? It sounds like what you really want is functionality to support publishing metrics to multiple namespaces.

**Comment by herrsergio** [comment]
Originally yes, we are using a custom namespace for our metrics, and there are already some alarms set up using this namespace.

But we would like to also publish to the CWAgent namespace. I was told by AWS Support that currently multiple namespaces are not supported. So I was trying to have 2 agents running.
I've found the Docker image of the agent, and I'm currently making some tests.

**Comment by SaxyPandaBear** [comment]
Yeah my next suggestion would have been to try running a docker container with the agent in it, but I haven't tested it out myself.
