### ISSUE TITLE
auto_removal removes the recreated file when renaming and recreating

### ISSUE THREAD

**Issue by adossas-spdrm** [aws/amazon-cloudwatch-agent#678]
**Describe the bug**
In the [agent reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html#agent-faq)  the following rotation method is described as supported:

>Renaming existing log files with a numerical suffix, then re-creating the original empty log file. For example, /var/log/syslog.log is renamed /var/log/syslog.log.1. If /var/log/syslog.log.1 already exists from a previous rotation, it is renamed /var/log/syslog.log.2.

But when enabling `auto_removal` the agent would remove *syslog.log* instead of *syslog.log.1* and would start piping *syslog.log.1* to cloudwatch.

**Steps to reproduce**
Having a program that uses the log rotation mechanism mentioned above

1. Configure the agent with `auto_removal: true` and `file_path: /var/log/syslog.log*`
2. Wait for the first rotation to happen

**What did you expect to see?**

I would expect the agent to:
1.  remove *syslog.log.1*
2.  continue tailing the recreated *syslog.log* 

**What did you see instead?**
Instead the agent:
1. removed the recreated *syslog.log*
2. started tailing *syslog.log.1*

**What version did you use?**
Version:  `v1.247357.0`

**What config did you use?**

```json
	"logs": {
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/var/log/syslog.log*",
						"log_group_name": "syslog.log",
						"log_stream_name": "{instance_id}",
						"retention_in_days": 180,
						"auto_removal": true
					},
				]
			}
		}
	}
```

**Environment**
OS: RHEL 9.1.0

**Failing Testcase**

the following testcase could be added to `plugins\inputs\logfile\logfile_test.go`:

```go
func TestLogsFileRenameAndRecreateWithAutoRemoval(t *testing.T) {
	multilineWaitPeriod = 10 * time.Millisecond

	logEntryBeforeRecreate := "ContentBeforeRecreate"
	logEntryAfterRecreate := "ContentAfterRecreate"

	tmpfile, err := createTempFile("", "")
	defer os.Remove(tmpfile.Name())
	require.NoError(t, err)
	_, err = tmpfile.WriteString(logEntryBeforeRecreate + "\n")
	require.NoError(t, err)

	stateDir, err := ioutil.TempDir("", "state")
	require.NoError(t, err)
	defer os.Remove(stateDir)

	stateFileName := filepath.Join(stateDir, escapeFilePath(tmpfile.Name()))
	stateFile, err := os.OpenFile(stateFileName, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0644)
	require.NoError(t, err)
	_, err = stateFile.WriteString("0")
	require.NoError(t, err)
	err = stateFile.Close()
	require.NoError(t, err)
	defer os.Remove(stateFileName)

	tt := NewLogFile()
	tt.FileStateFolder = stateDir
	tt.Log = TestLogger{t}
	tt.FileConfig = []FileConfig{{FilePath: tmpfile.Name()+"*", FromBeginning: true, AutoRemoval: true }}
	tt.FileConfig[0].init()
	tt.started = true

	lsrcs := tt.FindLogSrc()
	if len(lsrcs) != 1 {
		t.Fatalf("%v log src was returned when 1 should be available", len(lsrcs))
	}

	lsrc := lsrcs[0]
	evts := make(chan logs.LogEvent)
	lsrc.SetOutput(func(e logs.LogEvent) {
		if e != nil {
			evts <- e
		}
	})

	go func() {
		time.Sleep(1 * time.Second)

		// recreate file
		err = os.Rename(tmpfile.Name(), tmpfile.Name()+".1")
		require.NoError(t, err)
		require.NoError(t, tmpfile.Close())

		tmpfile, err = os.OpenFile(tmpfile.Name(), os.O_RDWR|os.O_CREATE|os.O_EXCL, 0600)
		require.NoError(t, err)

		log.Println("Writing to tmpfile")
		_, err = tmpfile.WriteString(logEntryAfterRecreate + "\n")
		log.Printf("Written to tmpfile %v", tmpfile.Name())
		require.NoError(t, err)

	}()

	e := <-evts
	if e.Message() != logEntryBeforeRecreate {
		t.Errorf("Wrong log found before file replacement: \n%v\nExpecting:\n%v\n", e.Message(), logEntryBeforeRecreate)
	}
	defer lsrc.Stop()

	// Waiting 10 seconds for the recreated temp file to be detected is plenty sufficient on any OS.
	for start := time.Now(); time.Since(start) < 10*time.Second; {
		lsrcs = tt.FindLogSrc()
		if len(lsrcs) > 0 {
			break
		}
		time.Sleep(1 * time.Second)
	}
	if len(lsrcs) != 1 {
		t.Fatalf("%v log src was returned when 1 should be available", len(lsrcs))
	}
	lsrc = lsrcs[0]
	lsrc.SetOutput(func(e logs.LogEvent) {
		if e != nil {
			evts <- e
		}
	})

	e = <-evts
	log.Printf("Getting output %v", e)
	if e.Message() != logEntryAfterRecreate {
		t.Errorf("Wrong log found after file replacement: \n% v\nExpecting:\n% v\n", e.Message(), logEntryAfterRecreate)
	}

	lsrc.Stop()
	tt.Stop()
}
```

**Comment by SaxyPandaBear** [comment]
> I would expect the agent to:
remove syslog.log.1
continue tailing the recreated syslog.log

This is not how the agent behaves. You created tmpfile first, then tmpfile.1. The agent is going to find the latest log file by last-modification time, which is syslog.log.1 and start monitoring that because it is newer. If you are using log rotation and always appending to syslog.log, you should not rely on auto-removal to clean up

**Comment by adossas-spdrm** [comment]
@SaxyPandaBear I am not convinced that this would be the expected behavior of the agent. 
To be precise I'm not creating tmpfile first and then tmpfile.1,
but tmpfile is just renamed/moved to tmpfile.1 and in linux moving a file does not alter the modification date.
After that tmpfile is recreated thus being the newest one.

**Comment by SaxyPandaBear** [comment]
Thanks for diving into that. That makes sense. What are you using auto_removal for if you are copying and removing the previous file? It sounds like you already have a solution for log rotation. The `auto_removal` feature is not meant to be a standalone log rotator.

**Comment by SaxyPandaBear** [comment]
The ideal use case for using `auto_removal` is if you write to logs that are suffixed, like:
```bash 
/tmp/foo.log.2023-01-03-1 // log file created for the first hour
/tmp/foo.log.2023-01-03-2 // log file created for the second hour
/tmp/foo.log.2023-01-03-3 // etc
```

Then, when the agent detects the new file, `/tmp/foo.log.2023-01-03-2` after log rotation occurs, it will clean up the old log file and start monitoring the new one.

**Comment by adossas-spdrm** [comment]
My use case is the following:

```
/tmp/foo.log # the currently active log file
/tmp/foo.log.2023-02-06 # log file created for the past day
/tmp/foo.log.2023-02-05 # etc
```
Ideally, when log rotation occurs, I would like the agent to start monitoring foo.log from the beginning, and clean up the renamed `foo.log` now called e.g. `foo.log.2023-02-06`.

**Comment by SaxyPandaBear** [comment]
So your use case is not what `auto_removal` was intended for. 

Auto removal cleans up log files that it was monitoring when a newer log file is found. What you are looking for is regular log rotation. The CloudWatch agent does not support the form of log rotation that you are looking for.
