### ISSUE TITLE
ResourceNotFoundException: The specified log group does not exist.

### ISSUE THREAD

**Issue by vesubramanian** [aws/amazon-cloudwatch-agent#679]
**Describe the bug**
I am trying to configure CW Monitoring for Windows (System & Application) events and a Custom Application Log file. I used the configuration wizard to generate the config, however, it didn't add the agent section. I manually added it with debug=true and started the service. It created only 1 LogGroup (System) and the LogStream (instance_id). The Agent Log had the error "ResourceNotFoundException:The specified log group does not exist". The required permissions are available, since System Log Group did get created, although it threw error for the other Log groups.

**Steps to reproduce**
```json
{
	"agent": {
        "metrics_collection_interval": 60,
        "logfile": "c:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\amazon-cloudwatch-agent.log",
	"debug": true
      },
	"logs": {
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "C:\\Temp\\Logs\\*",
						"log_group_name": "{instance_id}",
						"log_stream_name": "MyCustomApp",
						"retention_in_days": 3
					}
				]
			},
			"windows_events": {
				"collect_list": [
					{
						"event_format": "xml",
						"event_levels": [
							"WARNING",
							"ERROR",
							"CRITICAL"
						],
						"event_name": "System",
						"log_group_name": "System",
						"log_stream_name": "{instance_id}",
						"retention_in_days": 3
					},
					{
						"event_format": "xml",
						"event_levels": [
							"WARNING",
							"ERROR",
							"CRITICAL"
						],
						"event_name": "Application",
						"log_group_name": "Application",
						"log_stream_name": "{instance_id}",
						"retention_in_days": 3
					}
				]
			}
		}
	},
	"metrics": {
		"aggregation_dimensions": [
			[
				"InstanceId"
			]
		],
		"append_dimensions": {
			"AutoScalingGroupName": "${aws:AutoScalingGroupName}",
			"ImageId": "${aws:ImageId}",
			"InstanceId": "${aws:InstanceId}",
			"InstanceType": "${aws:InstanceType}"
		},
		"metrics_collected": {
			"LogicalDisk": {
				"measurement": [
					"% Free Space"
				],
				"metrics_collection_interval": 60,
				"resources": [
					"*"
				]
			},
			"Memory": {
				"measurement": [
					"% Committed Bytes In Use"
				],
				"metrics_collection_interval": 60
			},
			"Paging File": {
				"measurement": [
					"% Usage"
				],
				"metrics_collection_interval": 60,
				"resources": [
					"*"
				]
			},
			"PhysicalDisk": {
				"measurement": [
					"% Disk Time"
				],
				"metrics_collection_interval": 60,
				"resources": [
					"*"
				]
			},
			"Processor": {
				"measurement": [
					"% User Time",
					"% Idle Time",
					"% Interrupt Time"
				],
				"metrics_collection_interval": 60,
				"resources": [
					"*"
				]
			}
		}
	}
}
```

Ran the command to start the Agent service from the Agent Location
.\amazon-cloudwatch-agent-ctl.ps1 -a fetch-config -m ec2 -s -c file:config.json

**What did you expect to see?**
3 Log Groups (Instance ID, Application and System) and the Log Streams inside those.

**What did you see instead?**
Only System Log Group was created with the Instance ID Log Stream. I saw the above mentioned error for the other Log groups. Also, no idea, in what order it creates.

**What version did you use?**
Agent Version - 1.3.50749

**What config did you use?**
Config provided above.

**Environment**
Windows 2019 EC2

Note: I also tried creating a single Log Group (Instance ID). That also didn't work. Also, I am wondering, why I can't create a Log Group globally (for all logs) and create Log Streams for System, Application, Custom etc.

**Comment by SaxyPandaBear** [comment]
edited the json in the markdown to make it easier to read

**Comment by SaxyPandaBear** [comment]
> Agent Version - 1.3.50749

Just as a note - this version is not accurate. There's some complication with the Windows version because our versioning scheme is not supported in building the MSI. You should check the version by running the ctl PowerShell script, or checking the CWAGENT_VERSION file in the installation folder.

**Comment by vesubramanian** [comment]
Thank you, The version from CWAGENT_VERSION file is 1.247357.0b252275

**Comment by SaxyPandaBear** [comment]
Sorry for the delay. Trying to understand the problem. Are you saying that the agent did not create the log groups and they don't exist for the windows event logs?

**Comment by mreza0100** [comment]
I have the very same issue, I create a dashboard and other resources, but at the first deployment, it fails because the resources that point out to the log group will fail since it's not there!
Maybe you can create the default log group not by the first call to lambda by only grading permission to create it for lambda, but by deployment in case it doesn't exist.
