### ISSUE TITLE
Glob not working as intended for collect_list.file_path

### ISSUE THREAD

**Issue by yongkang93** [aws/amazon-cloudwatch-agent#684]
**Describe the bug**
The glob syntax does not seem to be working as intended.

Given that I have the following files.

1. /tmp/example.txt
2. /tmp/example.txt_\<date> (e.g. /tmp/example.txt_20230207)
3. /tmp/example.txt.lck

I want to pipe example.txt and example.txt_\<date> to CloudWatch and exclude example.txt.lck.

Following Glob syntax (as mentioned in the [official document](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html) that it uses Glob), "/tmp/example.txt*(!(.lck))" should do the trick. However, when applied the configuration, it is not sending any of the above files to CloudWatch.

I have tested with /tmp/example.txt* and it works, but it is **sending all 3 files**. So at the very least, I know that my CloudWatch Agent is working.

Any pointers?

**Steps to reproduce**
Have CloudWatch Agent running on an EC2 machine.
Configure CloudWatch Agent to collect /tmp/example.txt*(!(.lck))
SSH into the EC2 machine and create 3 files.

1. /tmp/example.txt
2. /tmp/example.txt_20230207
3. /tmp/example.txt.lck

**What did you expect to see?**
Only /tmp/example.txt and /tmp/example.txt_20230207 should be piped to CloudWatch.

**What did you see instead?**
Nothing is piped to CloudWatch.

**What version did you use?**
v1.247354.0

**Comment by adam-mateen** [comment]
I think you want:
```
"/tmp/example.*[!l][!c][!k]"
```

the public AWS docs you linked link to this go package:
https://github.com/gobwas/glob
Using this specific go package with your example:
https://go.dev/play/p/30w3YmExzvS
```
package main

import (
	"fmt"
	"github.com/gobwas/glob"
)

func main() {
	var g glob.Glob
	// create simple glob
	g = glob.MustCompile("/tmp/example.txt*(!(.lck))")
	fmt.Println(g.Match("/tmp/example.txt"))
	fmt.Println(g.Match("/tmp/example.txt_20230207"))
	fmt.Println(g.Match("/tmp/example.txt.lck"))
}
```

returns:
```
false
false
false
```

Using the string `"/tmp/example.*[!l][!c][!k]"` I get:
```
false
false
true
```
