### ISSUE TITLE
AWS documentation does not show support for Ubuntu22.04

### ISSUE THREAD

**Issue by glenn9259** [aws/amazon-cloudwatch-agent#685]
The latest release supports Ubuntu server 22.04,
however documents on AWS does not show that.
For example:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html

Some customers are finding this confusing,
so if it possible please add support for Ubuntu server 22.04 on the documents.

**Comment by neuquen** [comment]
+1, it confused me too (if it actually is supported).

**Comment by muellerk22** [comment]
Is it supported?

**Comment by okankoAMZ** [comment]
On the [document](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html) it is shown that ubuntu 22.04 is supported.
<img width="1115" alt="image" src="https://github.com/aws/amazon-cloudwatch-agent/assets/107267850/b8911963-a14d-43dc-9a30-affee0691418">
