### ISSUE TITLE
Arm support for Debian

### ISSUE THREAD

**Issue by maximeroma** [aws/amazon-cloudwatch-agent#722]
**Is your feature request related to a problem? Please describe.**
We have an internal process to build ami using ansible and packer. Actually, we use a lot the famous christiangda ansible-role-amazon-cloudwatch-agent. More and more clients wants to use the graviton instance but we can't propose it right now because there are no support for arm with debian. I think we are not alone in this case and this feature will be a big unblocker.            

**Describe the solution you'd like**
Add a downloadable link for debian like this: "https://s3.amazonaws.com/amazoncloudwatch-agent/debian/arm64/latest/amazon-cloudwatch-agent.deb" and the related signature file link.

**Comment by sethAmazon** [comment]
s3://amazoncloudwatch-agent/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb 
This should work, since the binary is not different for Ubuntu and Debian. I'm uncertain if we have tests for this, but you are welcome to check it out for now.

**Comment by maximeroma** [comment]
@sethAmazon it works but as we provide our instance with ansible role we need to overide it to works as expected. Ansible interpolate the s3 url with os and arch where is running. https://s3.amazonaws.com/amazoncloudwatch-agent/{{os}}/{{arch}}/latest/amazon-cloudwatch-agent.deb. We can make it works with an override of ansible var but it's just a hack. It will be nicer to have this url available. A lot of people think debian and arm are not supported because of this

**Comment by peteroruba** [comment]
@maximeroma you are definitely not alone ;) This is our only blocker that keeps us from migrating our EC2 fleet to ARM64

**Comment by okankoAMZ** [comment]
I have created a backlog item for this thank you for brining this to our attention

**Comment by sethAmazon** [comment]
Hi, we intend to add support in our s3 bucket.

We would like to collect metrics on customers moving from amd64 to arm64 CPU. Would any of you be willing to send us information of your fleet's CPU usage using amd64 vs. arm64?

**Comment by okankoAMZ** [comment]
We have added support for arm64. It can be found in this documentation here: [Install-CloudWatch-Agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html)
