### ISSUE TITLE
make release fails on SEH1

### ISSUE THREAD

**Issue by vidalhe** [aws/amazon-cloudwatch-agent#729]
**Describe the bug**
Download repo locally.  make build works but make release fails on SEH1

**Steps to reproduce**
Download repo locally.  make build works but make release fails on SEH1

**What did you expect to see?**
build/bin/linux/arm64/amazon-cloudwatch-agent.rpm
build/bin/linux/amd64/amazon-cloudwatch-agent.rpm
build/bin/linux/arm64/amazon-cloudwatch-agent.deb
build/bin/linux/amd64/amazon-cloudwatch-agent.deb
build/bin/windows/amd64/amazon-cloudwatch-agent.zip
build/bin/darwin/amd64/amazon-cloudwatch-agent.tar.gz

**What did you see instead?**
ok      github.com/aws/amazon-cloudwatch-agent/metric/distribution/regular      0.289s  coverage: 79.6% of statements
--- FAIL: TestSEH1Distribution (0.00s)
    seh1_distribution_test.go:32: 
                Error Trace:    /Users/mjh033/GitLabRepos/GitHub/amazon-cloudwatch-agent/metric/distribution/seh1/seh1_distribution_test.go:32
                Error:          Not equal: 
                                expected: map[float64]float64{20.13119624437727:1, 29.474084421392764:1, 52.21513847164702:1}
                                actual  : map[float64]float64{20.13119624437727:1, 29.47408442139276:1, 52.21513847164702:1}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,3 +2,3 @@
                                  (float64) 20.13119624437727: (float64) 1,
                                - (float64) 29.474084421392764: (float64) 1,
                                + (float64) 29.47408442139276: (float64) 1,
                                  (float64) 52.21513847164702: (float64) 1
                Test:           TestSEH1Distribution
    seh1_distribution_test.go:73: 
                Error Trace:    /Users/mjh033/GitLabRepos/GitHub/amazon-cloudwatch-agent/metric/distribution/seh1/seh1_distribution_test.go:73
                Error:          Not equal: 
                                expected: map[float64]float64{20.13119624437727:2, 22.144315868814992:3, 29.474084421392764:1, 52.21513847164702:1}
                                actual  : map[float64]float64{20.13119624437727:2, 22.144315868814992:3, 29.47408442139276:1, 52.21513847164702:1}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -3,3 +3,3 @@
                                  (float64) 22.144315868814992: (float64) 3,
                                - (float64) 29.474084421392764: (float64) 1,
                                + (float64) 29.47408442139276: (float64) 1,
                                  (float64) 52.21513847164702: (float64) 1
                Test:           TestSEH1Distribution
FAIL
        github.com/aws/amazon-cloudwatch-agent/metric/distribution/seh1 coverage: 74.6% of statements
FAIL    github.com/aws/amazon-cloudwatch-agent/metric/distribution/seh1 0.361s

**What version did you use?**
Version: 1.247358

**What config did you use?**

RPM version 4.18.1

**Environment**
OS: MacOS 13.3

**Additional context**

**Comment by SaxyPandaBear** [comment]
Thanks for reporting this. What architecture are you running on? I can't reproduce this on my Intel MacBook.

**Comment by SaxyPandaBear** [comment]
On an AMD host, the test passes:
```
$ go test -v -run TestSEH1Distribution ./metric/distribution/seh1/
=== RUN   TestSEH1Distribution
--- PASS: TestSEH1Distribution (0.00s)
PASS
ok      github.com/aws/amazon-cloudwatch-agent/metric/distribution/seh1 0.003s
```

On an ARM host, the test consistently fails:
```
$ go test -v -run TestSEH1Distribution ./metric/distribution/seh1/
=== RUN   TestSEH1Distribution
    seh1_distribution_test.go:32: 
                Error Trace:    /home/ec2-user/amazon-cloudwatch-agent/metric/distribution/seh1/seh1_distribution_test.go:32
                Error:          Not equal: 
                                expected: map[float64]float64{20.13119624437727:1, 29.474084421392764:1, 52.21513847164702:1}
                                actual  : map[float64]float64{20.13119624437727:1, 29.47408442139276:1, 52.21513847164702:1}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,3 +2,3 @@
                                  (float64) 20.13119624437727: (float64) 1,
                                - (float64) 29.474084421392764: (float64) 1,
                                + (float64) 29.47408442139276: (float64) 1,
                                  (float64) 52.21513847164702: (float64) 1
                Test:           TestSEH1Distribution
    seh1_distribution_test.go:73: 
                Error Trace:    /home/ec2-user/amazon-cloudwatch-agent/metric/distribution/seh1/seh1_distribution_test.go:73
                Error:          Not equal: 
                                expected: map[float64]float64{20.13119624437727:2, 22.144315868814992:3, 29.474084421392764:1, 52.21513847164702:1}
                                actual  : map[float64]float64{20.13119624437727:2, 22.144315868814992:3, 29.47408442139276:1, 52.21513847164702:1}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -3,3 +3,3 @@
                                  (float64) 22.144315868814992: (float64) 3,
                                - (float64) 29.474084421392764: (float64) 1,
                                + (float64) 29.47408442139276: (float64) 1,
                                  (float64) 52.21513847164702: (float64) 1
                Test:           TestSEH1Distribution
--- FAIL: TestSEH1Distribution (0.00s)
FAIL
FAIL    github.com/aws/amazon-cloudwatch-agent/metric/distribution/seh1 0.004s
FAIL
```
