### ISSUE TITLE
Question: when pushing Nvidia metrics, such as nvidia_smi_memory_used, can I adjust them in the CloudWatch Metrics UI?

### ISSUE THREAD

**Issue by matthewcummings** [aws/amazon-cloudwatch-agent#784]
**Is your feature request related to a problem? Please describe.**
I've been sending GPU metrics to CloudWatch per https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-NVIDIA-GPU.html. 

I would like to display the values as megabytes, but they appear to be transmitted as bytes. Is there a way to add the math in the CloudWatch metrics UI or could I make the CloudWatch agent convert the values before sending them?

**Comment by jefchien** [comment]
This can be done in the CloudWatch console by adding metric math. See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html
