### ISSUE TITLE
Support setting log retention to 3 years

### ISSUE THREAD

**Issue by markdboyd** [aws/amazon-cloudwatch-agent#787]
**Is your feature request related to a problem? Please describe.**

1096 days is a valid value for the retention period of Cloudwatch logs: 

> The number of days to retain the log events in the specified log group. Possible values are: 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, **1096**, 1827, 2192, 2557, 2922, 3288, and 3653.

From https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#CWL-PutRetentionPolicy-request-retentionInDays

But you cannot specify 1096 as a value for retention in days to the agent because the schema does not support it.

**Describe the solution you'd like**

Add 1096 days as a supported schema value for Cloudwatch log retention days to this agent.

**Describe alternatives you've considered**

None

**Comment by SaxyPandaBear** [comment]
Thanks for the callout and the associated PR! I wasn't aware that the API made an update to support 3 year retention. Looks like this was done 6ish months ago
