### ISSUE TITLE
Shuts down after a few hours while system is still running.

### ISSUE THREAD

**Issue by abertolli** [aws/amazon-cloudwatch-agent#833]
**Describe the bug**
After a number of hours, the cloudwatch agent simply shuts down.  It appears to happen on all hosts (we are running RHEL 7).

**Steps to reproduce**
Either `systemctl restart amazon-cloudwatch-agent` or reboot the host

**What did you expect to see?**
Cloudwatch agent start up, and continuously send logs and metrics without stopping.

**What did you see instead?**
Agent runs for anywhere between 4 to 24 hours, then ends with the log messages:
```
2023-08-26T03:37:01Z I! Profiler is stopped during shutdown
2023-08-26T03:37:01.684Z	info	otelcol/collector.go:227	Received signal from OS	{"signal": "terminated"}
2023-08-26T03:37:01.684Z	info	service/service.go:157	Starting shutdown...
2023-08-26T03:37:01.733Z	info	extensions/extensions.go:44	Stopping extensions...
2023-08-26T03:37:01.733Z	info	service/service.go:171	Shutdown complete.
```

**What version did you use?**
amazon-cloudwatch-agent-1.300026.2b172-1.x86_64

**What config did you use?**
/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/amazon-cloudwatch-agent
```
{
	"agent": {
		"run_as_user": "root"
	},

	"logs": {
		"log_stream_name": "{local_hostname}",
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
						"log_group_name": "ec2/amazon-cloudwatch-agent",
						"timestamp_format": "%Y-%m-%dT%H:%M:%S",
						"timezone": "UTC",
						"multi_line_start_pattern": "{timestamp_format}"
					}
				]
			}
		}
	},

	"metrics": {
		"metrics_collected": {
			"procstat": [
				{
					"pattern": "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				}
			]
		}
	}
}
```

/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/amazon-inspector-agent
```
{
	"metrics": {
		"metrics_collected": {
			"procstat": [
				{
					"pattern": "/opt/aws/awsagent/bin/awsagent",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				}
			]
		}
	}
}
```

/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/amazon-ssm-agent
```
{
	"metrics": {
		"metrics_collected": {
			"procstat": [
				{
					"pattern": "/usr/bin/amazon-ssm-agent",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				},
				{
					"pattern": "/usr/bin/ssm-agent-worker",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				}
			]
		}
	}
}
```

/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/auditd
```
{
	"logs": {
		"log_stream_name": "{local_hostname}",
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/var/log/audit/audit.log",
						"log_group_name": "ec2/auditd",
						"timestamp_format": "%b %-d %H:%M:%S",
						"timezone": "UTC"
					}
				]
			}
		}
	}
}
```

/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/disk
```
{
	"metrics": {
		"metrics_collected": {
			"disk": {
				"resources": [
					"*"
				],
				"measurement": [
					"used_percent"
				],
				"ignore_file_system_types": [
					"sysfs",
					"devtmpfs",
					"tmpfs",
					"nfs",
					"cifs",
					"mvfs",
					"fuse.s3fs"
				],
				"drop_device": true
			}
		}
	}
}
```

/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/mcafee
```
{
	"logs": {
		"log_stream_name": "{local_hostname}",
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/var/McAfee/ens/log/tp/mfeoasmgr.log",
						"log_group_name": "ec2/McAfee/mfeoasmgr",
						"timestamp_format": "%b %-d %H:%M:%S",
						"timezone": "UTC"
					},
					{
						"file_path": "/var/McAfee/ens/log/tp/mfetpd.log",
						"log_group_name": "ec2/McAfee/mfetpd",
						"timestamp_format": "%b %-d %H:%M:%S",
						"timezone": "UTC"
					}
				]
			}
		}
	},

	"metrics": {
		"metrics_collected": {
			"procstat": [
				{
					"pattern": "/opt/McAfee/agent/bin/macmnsvc",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				},
				{
					"pattern": "/opt/McAfee/agent/bin/macompatsvc",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				},
				{
					"pattern": "/opt/McAfee/agent/bin/masvc",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				},
				{
					"pattern": "/opt/McAfee/ens/esp/bin/mfeespd",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				},
				{
					"pattern": "/opt/McAfee/ens/tp/bin/mfetpd",
					"measurement": [
						"cpu_usage",
						"memory_rss"
					]
				}
			]
		}
	}

}
```

/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/syslog
```
{
	"logs": {
		"log_stream_name": "{local_hostname}",
		"logs_collected": {
			"files": {
				"collect_list": [
					{
						"file_path": "/var/log/secure",
						"log_group_name": "ec2/syslog/secure",
						"timestamp_format": "%b %-d %H:%M:%S",
						"timezone": "UTC"
					},
					{
						"file_path": "/var/log/messages",
						"log_group_name": "ec2/syslog/messages",
						"timestamp_format": "%b %-d %H:%M:%S",
						"timezone": "UTC"
					}
				]
			}
		}
	}
}
```

**Environment**
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Additional context**
Logs appear to be sent fine during the time it is running.  We do get warnings continuously that it can't get the metrics for specific processes above with:
```
2023-08-28T17:25:58.212Z	warn	accumulator/accumulator.go:124	Filter and convert failed	{"kind": "receiver", "name": "telegraf_procstat/143831642", "data_type": "metrics", "name": "procstat_lookup", "tags": {"host":"host01","pattern":"/opt/McAfee/ens/esp/bin/mfeespd","pid_finder":"native"}, "fields": {}, "type": 3, "error": "empty metrics after filtering metrics"}
```

But we think this is an unrelated problem.

**Comment by SaxyPandaBear** [comment]
Like you said, the failure logs for getting metrics are unrelated. 

Do you see any obvious errors in journald logs? I think it should be `sudo journalctl -u amazon-cloudwatch-agent` to view them. Otherwise, there isn't anything that should be causing the agent to crash _gracefully_. Based on the information presented, there is likely something else that is stopping the agent.

**Comment by abertolli** [comment]
Thanks for taking a look.  Not seeing anything that looks like the cause.  It complains about the default .json file not existing, but we are using the .d directory for our config, and it seems to start up this way fine.

```
-- Logs begin at Mon 2023-08-28 15:00:53 UTC, end at Mon 2023-08-28 18:37:37 UTC. --
Aug 28 15:01:01 host01 systemd[1]: Started Amazon CloudWatch Agent.
Aug 28 15:01:02 host01 start-amazon-cloudwatch-agent[1037]: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json does not exist
Aug 28 15:01:02 host01 start-amazon-cloudwatch-agent[1037]: I! Detecting run_as_user...
Aug 28 16:31:01 host01 systemd[1]: Stopping Amazon CloudWatch Agent...
Aug 28 16:31:06 host01 systemd[1]: Stopped Amazon CloudWatch Agent.
```

I've searched extensively online, and have found no other reports of this specific issue.  We have AWS support, and I'm going to open a case with them as well just to see what they say.  Additionally I may start paring down the number of configs we have to something simpler to see if that helps.  But the fact that in runs for a while and then stops makes me think the configs are fine.

I looked through the code here a little bit, but wasn't familiar enough to figure out what the conditions are that cause it to shut down gracefully on its own.

**Comment by abertolli** [comment]
Oh by the way, I have seen reports of issues with SSM.  We do have SSM agent on the systems, but we haven't specifically configured it to shut down the cloudwatch agent.  How would I go about investigating whether or not there is some kind of conflict between SSM and the cloudwatch agent?

**Comment by abertolli** [comment]
Ending logs from the same system:

ssm:
```
2023-08-28 15:01:47 INFO [ssm-document-worker] [825d4a91-bb1e-4961-a648-aa7d1c81f7e8.2023-08-28T15-01-26.566Z] Stop the cloudwatchlogs publisher
2023-08-28 15:05:18 INFO [ssm-document-worker] [a0c4d4f1-2861-4a9a-8443-085640fda197] Stop the cloudwatchlogs publisher
```

cloudwatch:
```
2023-08-28T16:31:01Z I! Profiler is stopped during shutdown
2023-08-28T16:31:01.618Z	info	otelcol/collector.go:227	Received signal from OS	{"signal": "terminated"}
2023-08-28T16:31:01.618Z	info	service/service.go:157	Starting shutdown...
2023-08-28T16:31:06.656Z	info	extensions/extensions.go:44	Stopping extensions...
2023-08-28T16:31:06.656Z	info	service/service.go:171	Shutdown complete.
```

Question is, given the timestamps, is it possible that SSM is stopping the cloudwatch agent?  It seems the message from SSM is an hour and a half before cloudwatch actually shuts down.  Normally I'd discount the connection due to the time delay, but does that sound reasonable?

**Comment by SaxyPandaBear** [comment]
You're free to ignore the log about the default JSON file not existing. We always check for that. 

> I looked through the code here a little bit, but wasn't familiar enough to figure out what the conditions are that cause it to shut down gracefully on its own.

That's the thing - there isn't really a set of conditions where the agent will shut itself down gracefully. A while back, the agent had a code path that would silently panic, but we've since tried to add logs before panics to avoid this - also the panic was still visible in journal logs. 

If there's no obvious panic in the agent logs, whether it is the agent log file or from journal/systemd, I'm leaning towards some other process that is shutting it down.

---
Sounds like you identified that SSM is doing _something_. Now is where it gets a little tricky, because the logs you pasted from the SSM worker could be relevant or they could not. There is an old/legacy CloudWatch logs SSM plugin, which I think should get automatically shut down/turned off during SSM automation requests, but I don't remember what triggers that. 

Are you using SSM to install/configure/start the agent? You might be able to trace through commands executed by SSM via the AWS console to see what actually ran in the region, and on what hosts/targets. That might narrow down the issue

**Comment by abertolli** [comment]
Thanks.  I will investigate what SSM is doing.  Also, is there a way to get debug logs from the cloudwatch-agent?

**Comment by SaxyPandaBear** [comment]
Debug logs from the agent probably wouldn't really help identify what is shutting it down, but there are a couple ways now you can turn it on. The main, [documented](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/troubleshooting-CloudWatch-Agent.html#CloudWatch-Agent-troubleshooting-loginfo) way is to add `debug: true` in your agent config, but #293 introduced a way to turn on debug logs at runtime without restarting the agent. Namely, by running `sudo /opt/aws/amazon-cloudwatch/bin/amazon-cloudwatch-agent-ctl -a set-log-level -l DEBUG`

**Comment by abertolli** [comment]
Took a look at SSM, and the cloudwatch references are about SSM agent's own internal tool to send data to cloudwatch, and it hasn't been shutting it down.

However I do think we found the culprit to be a misbehaving logrotate script that was being used to rotate /opt/aws/amazon-cloud-watch/logs/amazon-cloud-watch.log

After getting the advice here that it appears the cloudwatch agent is shutting down gracefully, if I had it to do over, I would immediately investigate /var/log/messages for clues on why it was being shut down.
