### ISSUE TITLE
Removal of v2.0.4 tag

### ISSUE THREAD

**Issue by owestenra01** [aws/amazon-cloudwatch-agent#852]
This tag was released years ago but the majority of the newer releases are a major version behind. In my opinion, this tag should be removed so it can be utilised later on.

https://github.com/aws/amazon-cloudwatch-agent/releases/tag/v2.0.4

**Comment by okankoAMZ** [comment]
At Amazon, we consider customer experience as our number one priority in all our endeavors. We believe that the removal of this tag does not yield any tangible benefits for our valued customers. Consequently, we have decided to retain this tag until further notice.
