### ISSUE TITLE
There is no response to issues on this repository

### ISSUE THREAD

**Issue by SamStephens** [aws/amazon-cloudwatch-agent#863]
Tagging @chadpatel because that's the only AWS related account I can see contributing to this repository.

There has been no response to issues left on this repository for at least three months. Please prioritise responding to them.

Alternatively, if AWS no longer responds to issues on this repository, turn off Issues in the repository settings so we don't waste our time on issues that will never be actioned.

It's disrespectful of our time and the contribution we're trying to make to the ecosystem when we're allowed to put work into issues that will never be actioned.

**Comment by kevin-aws** [comment]
Hi @SamStephens,

Thank you for bringing this issue to our attention. 

At AWS, we work backwards from our customers. We've recently been heads-down bringing support for AWS X-Ray and OpenTelemetry traces to Amazon CloudWatch agent, enabling customers to collect metrics, logs and traces in an interoperable way, with a single agent. 

However, our focus on the 1.3x agent releases has been reflected in the timeliness of our responses to issues in this repo. The community plays an important part in the development of CloudWatch agent, and the CloudWatch agent team is committed to working with the community on your key issues and PRs.

Kevin Wagner
Senior Technical Product Manager
Amazon CloudWatch Agent

**Comment by SamStephens** [comment]
@kevin-aws thanks for responding.

It's not really great neglecting your existing ecosystem in order to build out new features though.

We all know how much money AWS makes; it's hard to see why AWS cannot resource both new initiatives and maintenance on the existing client libraries. Even just basic issue triage, so we know that we're not actually using an unmaintained component.

The success of an AWS service depends on the end to end developer experience, which includes the issue raising experience.

> [...] the CloudWatch agent team is committed to working with the community on your key issues and PRs.

Then demonstrate it. Start triaging these issues. Three months of silence is not working with the community. Show us your values, don't tell us them.
