### ISSUE TITLE
amazon-cloudwatch-agent-ctl doesn't show version information of installed CloudWatch agent

### ISSUE THREAD

**Issue by rgoltz** [aws/amazon-cloudwatch-agent#95]
**Describe the bug**
I've installed (or updated) the Amazon CloudWatch agent to version amazon-cloudwatch-agent-1.247345.31-1.amzn2.x86_64 via package-manager. Once you request the current agent version via amazon-cloudwatch-agent-ctl you getting no value for key "version" within JSON.

**CloudWatch version number**
1.247345.31-1

**Platform/OS/Hardware/Device**
Linux/Amazon Linux 2/EC2

**To Reproduce (observed behavior)**
* install 1.247345.31-1 on Amazon Linux 2 (please use exact this version - see 'Additional context') via yum
* issue the command on the shell:
`/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status`
```
{
  "status": "running",
  "starttime": "2020-09-20T16:17:38+0000",
  "version": ""
}
```

**Expected behavior**
I get the currently installed agent version within the returned JSON by using amazon-cloudwatch-agent-ctl.

**Additional context**
The above-named package is the current [checked at 21.09.2020] package within Amazon Linux 2 Repository "amzn2-core". Currently, all local packages/versions within my OS are managed by yum. Having this said, a potential fix needs to be available via Repository "amzn2-core" as well.

**Comment by yimuniao** [comment]
Thanks for reporting this issue.  It will be fixed in next release.

For the workaround, could you use `/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -version` instead?

**Comment by rgoltz** [comment]
@yimuniao - Thanks for the information and announcement that it getting fixed in the next version. Please mind that we are consuming from Repository "amzn2-core", so I'm assume it will be available there as well soon afterwards. You will link this issue along with the code-fix here in this github project?

Your workaround perfectly cover my current use-case. By running this command, I'm able to collect the local version-information via SSM again. I've just switched the code from parsing the JSON to working with the returned String. Thanks 👍

**Comment by haojhcwa** [comment]
@rgoltz the issue is caused by our script that prepares for the AL2 package which is part of the AL2 source repo, and not hosted in here at the moment, thus we are unable to link the commit.
The fix would be rolled out in next AL2 update in a few weeks I believe.
Thank you.

**Comment by rgoltz** [comment]
I can see that our AL2 instances here within eu-central-1 got an update via `yum update amazon-cloudwatch-agent`. The agent moved forward from 1.247345.31-1 to 1.247345.35-1. Once the update is applied, the ctl command new returning the version information:

```
[user@amzn2]# /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status
{
  "status": "running",
  "starttime": "2020-10-03T07:04:51+0000",
  "version": "1.247345.35"
}

```
I'm going to close the issue, since it's fixed within Amazon Linux 2 default repo. Thanks! @yimuniao @haojhcwa
